### ISSUE TITLE
Replace usage of [Preserve] attribute in our code

### ISSUE THREAD

**Issue by radekdoulik** [dotnet/android#5197]
Use the [DynamicDependencyAttribute](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.codeanalysis.dynamicdependencyattribute?view=net-5.0) instead.

For non-NET5/6 build we will need "fake" version of that attribute.

**Comment by jonathanpeppers** [comment]
We still have usage of this in .NET 7: https://github.com/xamarin/xamarin-android/blob/328644ac84170d4fb1e3ac2be6a42509170047f3/src/Mono.Android/Java.Lang/Object.cs#L84-L85
