### ISSUE TITLE
`InstallAndroidDependencies` target doesn't install platform-tools and other necessary parts of the SDK.

### ISSUE THREAD

**Issue by Lauriethefish** [dotnet/android#7284]
### Android application type

Android for .NET (net6.0-android, etc.)

### Affected platform version

.NET 6.0.400

### Description

When installing the android SDK using the `InstallAndroidDependencies` target, the downloaded SDK is missing key tools, such as aapt and `platform-tools`:
```
laurie@d95389ff63a7:/opt/android-sdk$ ls
platforms
```
This causes a build with the installed SDK to fail with error XA5300, since Xamarin discards your selected SDK directory when it thinks it's invalid. (perhaps a better error message would be great here, but not super important for this issue).

It would be great if this could be fixed since this target is very, very helpful for CI.

### Steps to Reproduce

1. Start a docker container with the `mcr.microsoft.com/dotnet/sdk:6.0` image.
2. Create a new user, make them a sudoer, and log into the user with `su`.
3. Install the android workload `sudo dotnet workload install android`.
4. Create a new net6.0-android project: `sudo dotnet new android -o example && cd example`.
5. Restore the project: `sudo dotnet restore ./example.csproj`
6. Invoke `InstallAndroidDependencies` to download the SDK: `sudo dotnet msbuild ./example.csproj -t:InstallAndroidDependencies -p:AndroidSdkDirectory=/opt/android-sdk -p:AcceptAndroidSDKLicenses=true`
7. Attempt to use the new android SDK directory to build the project: `sudo dotnet publish -c Release -p:AndroidSdkDirectory=/opt/android-sdk`.
You will then receive the error: ```/usr/share/dotnet/packs/Microsoft.Android.Sdk.Linux/32.0.448/tools/Xamarin.Android.Tooling.targets(69,5): error XA5300: The Android SDK directory could not be found. Check that the Android SDK Manager in Visual Studio shows a valid
installation. To use a custom SDK path for a command line build, set the 'AndroidSdkDirectory' MSBuild property to the custom path. [/home/laurie/example/example.csproj]```

### Did you find any workaround?

No workaround currently, I tried installing the SDK with `sudo apt-get install -y android-sdk`, but unfortunately that SDK only targets API level 29, and we need API level 31 for net6.0-android.

### Relevant log output

See comment for diagnostic logs of both `InstallAndroidDepencies` and `publish`.

**Comment by Lauriethefish** [comment]
Logs here.
[Publish.log](https://github.com/xamarin/xamarin-android/files/9383570/Publish.log)
[InstallAndroidDependencies.log](https://github.com/xamarin/xamarin-android/files/9383571/InstallAndroidDependencies.log)

**Comment by Lauriethefish** [comment]
Hello, it's been a while, any chance this could be triaged?

**Comment by jonathanpeppers** [comment]
@dellis1972 there are some interesting logs like:
```
Could not retrieve Pkg.Revision from /opt/android-sdk/tools/source.properties, r0 assumed (TaskId:21)
```

Is it possible you can't build Android projects without `tools` installed? I'm not sure if that is the underlying issue, or if it just couldn't install `tools`.

**Comment by dellis1972** [comment]
I have no idea. From the log it looks like we are calculating the dependencies correctly. 

```
Dependencies=
   platforms/android-31
   build-tools/32.0.0
           Version=32.0.0
   platform-tools
           Version=33.0.2
   cmdline-tools/7.0
           Version=7.0 
```


We will probably need to get someone to look at the SDKManager code to see what is happening.

**Comment by jonpryor** [comment]
@Lauriethefish: is `/opt/android-sdk` writable by your user?

Some of the output of [InstallAndroidDependencies.log](https://github.com/xamarin/xamarin-android/files/9383571/InstallAndroidDependencies.log) looks reasonable:

```
Component Android SDK Platform-Tools r31.0.3 not present on the system
```

in that we detected that Platform-Tools wasn't present.  Yay.

What's odd is that the `Dependencies=` line that @dellis1972 [noted](https://github.com/xamarin/xamarin-android/issues/7284#issuecomment-1348855944), which lists `platform-tools` `Version=33.0.2`.  33.0.2 is *not* 31.0.3, so…why are we getting a log message mentioning `Platform-Tools r31.0.3` and not 33.0.2?

Later we see:

```
```

**Comment by Lauriethefish** [comment]
@jonpryor 
> is /opt/android-sdk writable by your user?
It is. Looking through the dockerfile I was debugging, msbuild is invoked as root.

**Comment by jonpryor** [comment]
@Lauriethefish: did you try the potential workaround I mentioned, updating your `.csproj` to contain:

```xml
<PropertyGroup>
  <AndroidSdkPlatformToolsVersion>31.0.3</AndroidSdkPlatformToolsVersion>
</PropertyGroup>
```

**Comment by Lauriethefish** [comment]
I will try it in a few hours and get back to you.

**Comment by Lauriethefish** [comment]
@jonpryor
The workaround did seem to fix the error of the SDK not being recognised, however, some parts of the SDK are still missing, e.g. aapt, which causes a new error.
[InstallAndroidDependencies.log](https://github.com/xamarin/xamarin-android/files/12464412/InstallAndroidDependencies.log)
[publish.log](https://github.com/xamarin/xamarin-android/files/12464413/publish.log)

**Comment by jonathanpeppers** [comment]
Are you using `AndroidUseAapt2=false` anywhere? The log isn't diagnositc, so I am not able to tell. I would remove this setting if you have it.

Do things fare any better if you use .NET 7 instead? The .NET 6 `android` workload is out of support:

    Microsoft.NET.EolTargetFrameworks.targets(35,5): warning NETSDK1202: The workload 'android' is out of support and will not receive security updates in the future. Please refer to https://aka.ms/maui-support-policy for more information about the support policy.

**Comment by Lauriethefish** [comment]
I'm not using `AndroidUseAapt2=false` anywhere, no. Strange, I thought I had set the log to diagnostic. 
Yeah, I noticed the workload was out of support. I will give .NET 7 a go at some point, out of time today though.

**Comment by jonathanpeppers** [comment]
It does seem like we should remove the logic looking for `aapt` here:

https://github.com/xamarin/xamarin-android/blob/a48a9c564c3ad5e18f1076c7521379fbfe6d669d/src/Xamarin.Android.Build.Tasks/Tasks/ResolveAndroidTooling.cs#L136-L140

And look for `aapt2` instead, but I do see it on disk:

![image](https://github.com/xamarin/xamarin-android/assets/840039/6b75e992-56c5-46a7-a068-c24c9155129e)

**Comment by dellis1972** [comment]
Looking at the log, it seems that the `build-tools` are not being installed.

```
Android package has no revision defined
         Could not retrieve Pkg.Revision from /opt/android-sdk/tools/source.properties, r0 assumed
         Dependency found: Android SDK Platform 31
         Dependency found: Android SDK Platform-Tools
         Adding component 'Android SDK Platform 31 r1 [Platform: API 31]'
         Adding component 'Android SDK Platform-Tools r31.0.3'
         Dependency to be installed: Android SDK Platform 31
         Dependency to be installed: Android SDK Platform-Tools
```

Further up we have

```
         Component Android SDK Platform-Tools r31.0.3 not present on the system
         Component Android SDK Command-line Tools r5.0 not present on the system
         Component Android SDK Command-line Tools (latest) r5.0 not present on the system
         Component Android SDK Build-Tools 30.0.3 r30.0.3 not present on the system
         Component Android SDK Build-Tools 30.0.2 r30.0.2 not present on the system
         Component Android Emulator r31.2.9 not present on the system
         Component Android Emulator r31.1.4 not present on the system
```

its likely you will need to override `AndroidSdkBuildToolsVersion` property as well to use one which exists for the platform-tools you are trying to instll. You will probably need to define `AndroidCommandLineToolsVersion` as well.

**Comment by jonpryor** [comment]
As the [investigation](https://github.com/dotnet/android/issues/7284#issuecomment-1692299361) was (partially) [verified](https://github.com/dotnet/android/issues/7284#issuecomment-1697337190), I'll assert that the issue is that our various MSBuild properties which control component versions was out of sync with the manifest used for installation.

This is something we're still improving (see #9155), but I think that this issue is *currently* fixed for .NET 8, and our unit tests should help keep things valid.
