### ISSUE TITLE
Cannot merge Android Manifest elements from class library

### ISSUE THREAD

**Issue by hansmbakker** [dotnet/android#8262]
### Android application type

.NET Android (net7.0-android, etc.)

### Affected platform version

VS 2022 17.8 Pre 1, .NET 8 preview 7

### Description

I want to create a Maui class library that uses [content provider queries to get data from another application](https://developer.android.com/guide/topics/providers/content-provider-basics).

For this, it is required to add the [`queries` element to the Android Manifest](https://developer.android.com/guide/topics/manifest/queries-element).

I want to automatically add the required element to the Android Manifest of the application project that consumes my library so that it works without manually modifying the Android manifest of that application.

I tried doing this using [`<AndroidManifestOverlay Include="somefile.xml" />` ](https://github.com/xamarin/xamarin-android/blob/79be326349d638584321d008e4cf51af3aa97eb9/Documentation/guides/building-apps/build-items.md#androidmanifestoverlay).

### Steps to Reproduce

1. Create .NET Maui App project
2. Create .NET Maui class library and add an xml file `QueriesPackageRegistration.xml` with these contents:
    ```xml
    <?xml version="1.0" encoding="utf-8"?>
    <manifest xmlns:android="http://schemas.android.com/apk/res/android">
      <queries>
        <package android:name="com.companyname.someappid" />
      </queries>
    </manifest>
    ```
3. Add `<AndroidManifestOverlay Include="QueriesPackageRegistration.xml" />` to the class library project file
4. Try adding `<AndroidManifestMerger>manifestmerger.jar</AndroidManifestMerger>` - no ideas whether this is still needed in xamarin-android 13?
3. Add a dependency on the class library to the App project
5. Deploy the app
6. See that the `queries` element is not output to the generated Android Manifest.

**Comment by hansmbakker** [comment]
I found somebody [write on StackOverflow](https://stackoverflow.com/a/71376166) that
> It appears that the manifestmerger is not able to merge the AndroidManifest.xml from multiple projects in the Android solution.

**Comment by jonathanpeppers** [comment]
Android class libraries do not contain an `AndroidManifest.xml`, as there is no mechanism to bundle and redistribute it. There isn't an MSBuild item group for the file type, etc.

However, what you *could* probably do for now as a workaround:

1. Make an `.aar` file -- it is just a `.zip` file with the extension renamed.
2. Put your `AndroidManifest.xml` in the root of the archive
3. Put the `.aar` file in your project directory (next to `.csproj`) file

We *do* have a way for `.aar` files to flow from class libraries to application projects. They also happen to support `AndroidManifest.xml` files.

/cc @dellis1972 if you have other ideas here.

**Comment by dellis1972** [comment]
The `AndroidManifestOverlay` will only work in the app project. The suggestion about packaging te file into an .aar "should" work.
We do have a way of packaging android resources into an aar for a clas library I think, so maybe just flagging it with `AndroidManifest` in the class library will work. If it doesn't we should probably add that as an option.

**Comment by hansmbakker** [comment]
Thank you both for the ideas! I'll try it early next week and share the outcome here.

**Comment by hansmbakker** [comment]
Outcomes:
- [Not working] Add AndroidManifest as .xml file to class library. Steps:
  - Add `<AndroidManifest>Platforms\Android\AndroidManifest.xml</AndroidManifest>` to the first `<PropertyGroup>` in the csproj file
  - Add `Platforms\Android\AndroidManifest.xml` containing
    ```xml
    <?xml version="1.0" encoding="utf-8"?>
    <manifest xmlns:android="http://schemas.android.com/apk/res/android">
      <queries>
        <package android:name="<somePackageName-intentionally-removed>" />
      </queries>
    </manifest>
    ```
- [Not working] Add AndroidManifest as .aar file to class library. Steps:
  1. Zipped the AndroidManifest.xml so that it is in the root of the zip
  1. Renamed the zip to `SomeAndroidManifestAdditions.aar`
  1. Put the .aar file in the project directory (next to .csproj) file

I verified both approaches by checking whether the contents of the AndroidManifest I wanted to merge ended up in `ConsumingAppProjectDir\obj\Debug\net8.0-android\AndroidManifest.xml`

Am I missing something?

Regarding
> We do have a way for .aar files to flow from class libraries to application projects.
Should this be picked up automatically?

**Comment by dellis1972** [comment]
Fix is up https://github.com/xamarin/xamarin-android/pull/8273.

**Comment by jpobst** [comment]
Should be fixed in https://github.com/xamarin/xamarin-android/pull/8273.

**Comment by jpobst** [comment]
My bad, that PR isn't merged.

**Comment by BernhardPollerspoeck** [comment]
Is this to be expected to be worked on in the near future?

**Comment by BernhardPollerspoeck** [comment]
so i read this correct, that it will take about 16 month until this is in production available? serious?

i apprechiate the effort and quick resonse though.
