### ISSUE TITLE
CodeAnalyzer suggestion: Application subclasses must provide activation constructor

### ISSUE THREAD

**Issue by jonpryor** [dotnet/android#8410]
### Android application type

Classic Xamarin.Android (MonoAndroid12.0, etc.), .NET Android (net7.0-android, etc.)

### Affected platform version

All

### Description

When subclassing `Android.App.Application`, the "Activation Constructor" `(IntPtr handle, JniHandleOwnership transfer)` must also be provided.  Failure to do so will result in runtime errors:

https://github.com/xamarin/xamarin-android/issues/8399

### Steps to Reproduce

1. `dotnet new android`
2. Add an Application subclass

    ```csharp
    [Application]
    public class MyApp : Application {
    }
    ```

3. run

This will crash, with `adb logcat` containing:

```
F mono-rt : [ERROR] FATAL UNHANDLED EXCEPTION: System.NotSupportedException: Unable to activate instance of type MyApp from native handle 0x7ff1f3b468 (key_handle 0x466b26f).
```

See also the [Java Activation](https://learn.microsoft.com/en-us/xamarin/android/internals/architecture#java-activation) documentation:

> There are two scenarios in which the (IntPtr, JniHandleOwnership) constructor must be manually provided on a Managed Callable Wrapper subclass:
>
> 1. [Android.App.Application](https://learn.microsoft.com/en-us/dotnet/api/android.app.application) is subclassed. Application is special; the default Application constructor will never be invoked, and the [(IntPtr, JniHandleOwnership) constructor must instead be provided](https://github.com/xamarin/monodroid-samples/blob/f01b5c31/SanityTests/Hello.cs#L105).

**Comment by dellis1972** [comment]
PR in progress https://github.com/dotnet/android/pull/9447
