### ISSUE TITLE
.net maui app crashes on launch if app data is not cleared

### ISSUE THREAD

**Issue by petarsamardzic96** [dotnet/android#8754]
### Android application type

.NET Android (net7.0-android, net8.0-android, etc.)

### Affected platform version

.net8-android

### Description

In my dotnet maui app, Debug and release versions work on emulator, but if I make apk file and install it on my device, it crashes on launch. After I go to app settings in my phone and clear data from application, everything works perfectly. It is notable that I have already installed apk of previous version, then deleted it and then installed new apk. I cant catch crash neither in logs nor in appcenter. What could be the problem, it seems that 

### Steps to Reproduce

1. Install apk on device
2. Delete it
3. Install other or same apk file of the same application
4. Launch

### Did you find any workaround?

Workaround would be clearing app data in app settings on phone:
1. Open App info
2. Go to Memory
3. Clear data

**Comment by grendello** [comment]
To record logcat, please issue these commands from the developer command prompt:

```bat
> adb shell setprop debug.mono.log default,assembly,mono_log_level=debug,mono_log_mask=all
> adb logcat -G 64M
> adb logcat -c
rem Start the application here, wait for it to crash, then 15 seconds more and:
> adb logcat -d > log.txt
```

Please attach `log.txt` produced by the above.

**Comment by petarsamardzic96** [comment]
[log.txt](https://github.com/xamarin/xamarin-android/files/14402713/log.txt)

**Comment by Dastenis** [comment]
I have the same issue at android 14

**Comment by Heraxizator** [comment]
I have the same problem. I haven't ever seen any crashes on Xaomi or android emulators. It crashes only some versions of Samsung, Honor, Techno, Relmi in my experience. So, it's cringe that NET MAUI is not supported as well as we need and Xamarin is not enabled cause Google Play requires Android 14. The old version had 0.15% of crashes, but the new version got 5% of crashes. And i can't solve this problem as author of this question. So, i want kill yourself. Thank you, Microsoft.

**Comment by grendello** [comment]
@Dastenis @Heraxizator if you provide me with logs as requested in [this comment](https://github.com/dotnet/android/issues/8754#issuecomment-1961633142) (the one attached here is not very useful, alas and it points to issues with a certificate, which can't do nothing about) then at least we'll have a chance to see what might be going on.  As of now, have no actionable information provided in this issue.

@Heraxizator I have no idea what you mean by `Xamarin is not enabled cause Google Play requires Android 14` - you can target your app for Android 14 and build a .NET8 app targetting it without any issues.  You do not need MAUI to create an app targetting Android.  Also, if you mention crashes, please provide some details about them, we can't do anything unless we know what's going on.  What is the crash, what are the logcat messages surrounding it, are there managed, java or native stack traces and, if yes, please provided them.

**Comment by jonpryor** [comment]
@Heraxizator [wrote](https://github.com/dotnet/android/issues/8754#issuecomment-2298567622):

> Xamarin is not enabled cause Google Play requires Android 14

You can continue to use Xamarin.Android 13.2 while *targeting* API-34 (Android 14) to update and deploy apps to the Google Play Store.  You just cannot use new APIs added in API-34.

Please see the [Xamarin.Android 13.2 Release Notes](https://learn.microsoft.com/en-us/previous-versions/xamarin/android/release-notes/13/13.2#target-api34).
