### ISSUE TITLE
When using `TrimMode=link` custom `AndroidHttpClientHandlerType` is not preserved

### ISSUE THREAD

**Issue by jonathanpeppers** [dotnet/android#8797]
### Android application type

.NET Android (net7.0-android, net8.0-android, etc.)

### Affected platform version

.NET 8, 9, etc.

### Description

If you use the project settings:
```xml
<TrimMode>link</TrimMode>
<AndroidHttpClientHandlerType>MyNamespace.MyCustomHandler</AndroidHttpClientHandlerType>
```

In this case, nothing would preserve `MyCustomHandler` and it would be trimmed away.

### Steps to Reproduce

Use project settings above.

### Did you find any workaround?

You could use either `[DynamicDependency]` or `[DynamicallyAccessedMembers]` to preserve the type. You could also instantiate the handler in code.

**Comment by jonpryor** [comment]
Related: whatever approach is used to preserve `$(AndroidHttpClientHandlerType)` -- likely a linker XML file -- should *also* be used to preserve `View` subclasses which are used within Android Layout `.axml` files.

This is partially touched upon in #8805, which had to add `[DynamicDependency(.All, typeof (Mono.Android_Test.Library.CustomTextView))` to ensure that the `View` subclass wasn't trimmed away.  `[DynamicDependency]` should not be required, ideally.
