### ISSUE TITLE
`TrimMode=full` seems to break android push notifications on MAUI .net 9 preview 3

### ISSUE THREAD

**Issue by jkommeren** [dotnet/android#8940]
### Android application type

.NET Android (net7.0-android, net8.0-android, etc.)

### Affected platform version

VS 2022 17.10.0 preview 7

### Description

Notifications don't arrive in some cases when "PublishTrimmed" is set to true and building it in Release mode (which is the default)

Point is: @jonathanpeppers suggested to create a new issue here if the issue still persisted on .net 9 preview 3. As far as I'm aware it has been an issue at least since .net 7, but also very likely .net 6.

Originally posted by @jonathanpeppers in https://github.com/xamarin/xamarin-android/issues/5652#issuecomment-2010266232
Also mentioned in https://github.com/dotnet/maui/issues/16014
And at least some people seem to be affected here https://github.com/dotnet/maui/discussions/19900

### Steps to Reproduce

1. Create project in .net 9 preview 3
2. Add firebase push notification support via Xamarin.Firebase.Messaging" Version="123.3.1.1", google-services.json, etc.
3. Create a channel with priority max or high, ask for permission to send notifications
4. Build project in release mode, setting PublishTrimmed to true (and AOT on or off, no difference)
5. Deploy it to Android device
6. Launch application
7. Send notification via Firebase Console with application open, specifying the channel
8. Notification does not arrive

### Did you find any workaround?

Set PublishTrimmed to False or deploying in debug mode fixes the issue immediately: Then the notification does arrive.

Also one odd thing: When the application is in the background, sending a notification via the Firebase console does pop up.
(But if it's sent as a Data message instead, the FirebaseMessagingService does not pick it up in foreground nor background. That is also fixed by using non-trimming or debug)

Maybe there's something I completely don't understand about Android notifications in MAUI, but the way I understand it, Debug should behave like Release mode in these cases right? And Non-trimmed vs Trimmed in Release mode too?

### Relevant log output

```shell
There is no log output. No unhandled exceptions. Nothing appears to happen when the notification is supposed to arrive.
```

**Comment by jkommeren** [comment]
Also, there is plenty of evidence people seem to be accepting "turning off trimming" as a "solution". But that's not how it should be right?

At least document what the is wrong. It took me weeks to figure out this workaround. I imagine many people giving up at some point.

https://stackoverflow.com/questions/76045900/net-maui-why-would-push-notifications-not-work-the-same-after-publishing

https://github.com/xamarin/xamarin-android/issues/5652

**Comment by tranb3r** [comment]
The problem here is that the trimmer is getting rid of an android service in the `Plugin.Firebase` library, responsible for receiving the notification.
I've already discussed this topic with @jonathanpeppers on discord.
My understanding is that the trimmer cannot "know" that an android service is used by your app. Maybe this could be fixed... who knows.
But the easiest fix (or workaround) is to make sure your app is preserving this service. You can skip trimming for the whole assembly, or add a DynamicDependency attribute in your code path.
A better fix would be to add an Initialize method in the lib, and add the DynamicDependency attribute in this method.
More details here: https://github.com/TobiasBuchholz/Plugin.Firebase/issues/144#issuecomment-1716038986

**Comment by tranb3r** [comment]
Also, about inspecting the apk, I've found that the easiest way to do it is to look into `YourApp\obj\Release\net8.0-android34.0\android-arm64\linked` folder. 
In this folder, you'll find all trimmed assemblies after your build, and you can easily open any dll in dnspy. 
In `Plugin.Firebase.CloudMessaging.dll`, look for `Plugin.Firebase.CloudMessaging.Platforms.Android.MyFirebaseMessagingService`. If it's missing, then the trimmer has been too aggressive, and your notifications won't work.

**Comment by jonathanpeppers** [comment]
@jkommeren so are you using `TrimMode=full` or default settings?

Services should not be trimmed away by default -- it should be using `TrimMode=partial` by default, which was the same as "SDK only" in the Xamarin days.

**Comment by tranb3r** [comment]
Yes this is with full trimming.

**Comment by jkommeren** [comment]
@jonathanpeppers  yes indeed with full trimming. I think I'm making progress. With the suggestions from tranb3r I have managed to get it working with .net 8 and his library Plugin.Firebase

I'm still a bit puzzled why my own implementation of the FirebaseMessagingService is not being fired though, even though it's present in the DLL (looking at DnSpy).

I think there's something I'm missing. 

I can create a sample project this weekend and have a proper go at .net 9 preview 3.

**Comment by jonathanpeppers** [comment]
I wouldn't expect `TrimMode=full` to work well in .NET 8, as we didn't solve all the trimmer warnings until .NET 9 Preview 3.

But it still seems like there might be some things that we should go test in .NET 8 w/ `TrimMode=full`:
* Broadcast receivers
* Services
* etc., etc.

I wonder if some of these are trimmed away and shouldn't be.
