### ISSUE TITLE
`InstallAndroidDependencies` target always warns about `tools`

### ISSUE THREAD

**Issue by jonpryor** [dotnet/android#8960]
### Android application type

.NET Android (net7.0-android, net8.0-android, etc.)

### Affected platform version

.NET 8.0.200

### Description

-

### Steps to Reproduce

On macOS (and elsewhere?), create a new .NET for Android project and then provision it:

```sh
% dotnet new android -n android-sdk-install
% cd android-sdk-install
% dotnet build -t:InstallAndroidDependencies \
  -p:AndroidSdkDirectory="`pwd`/sdk" \
  -p:JavaSdkDirectory="`pwd`/jdk" \
  -p:AcceptAndroidSDKLicenses=True
```

This runs without error, but it does emit two warnings:

```
/usr/local/share/dotnet/packs/Microsoft.Android.Sdk.Darwin/34.0.95/tools/Xamarin.Installer.Common.targets(12,3): warning : Android component "tools" is obsolete, please install "cmdline-tools"
/usr/local/share/dotnet/packs/Microsoft.Android.Sdk.Darwin/34.0.95/tools/Xamarin.Installer.Common.targets(12,3): warning : Trying to fallback to "tools"...
```

*Why* are these warnings emitted?

Considering that `tools` has been deprecated for _ages_ at this point and shouldn't be used, it would be nice if we didn't warn about it, *especially* when we're not even installing it!

---

While looking around in android-sdk-installer to figure out this issue, it would be nice to *also* understand these warnings shown in the diagnostic build log:

```
% dotnet build -t:InstallAndroidDependencies -v:diag \
  -p:AndroidSdkDirectory="`pwd`/sdk" \
  -p:JavaSdkDirectory="`pwd`/jdk" \
  -p:AcceptAndroidSDKLicenses=True > log.txt
```

`log.txt` contains:

```
warning : Dependency `platforms;android-34` should have been installed but could not be resolved. You can attempt to install it with: `…/android-sdk-install/sdk/cmdline-tools/11.0/bin/sdkmanager --install "platforms;android-34"`
warning : Dependency `build-tools;34.0.0` should have been installed but could not be resolved. You can attempt to install it with: `…/android-sdk-install/sdk/cmdline-tools/11.0/bin/sdkmanager --install "build-tools;34.0.0"`
warning : Dependency `platform-tools` should have been installed but could not be resolved. You can attempt to install it with: `…/android-sdk-install/sdk/cmdline-tools/11.0/bin/sdkmanager --install "platform-tools"`
warning : Dependency `cmdline-tools;11.0` should have been installed but could not be resolved. You can attempt to install it with: `…/android-sdk-install/sdk/cmdline-tools/11.0/bin/sdkmanager --install "cmdline-tools;11.0"`
```

Why aren't these packages found?  They were certainly installed the first time!

**Comment by pjcollins** [comment]
These issues should have been fixed by
https://github.com/xamarin/android-sdk-installer/commit/b5affa059c7bd9d5d6c89721a3ac8581ad8a1298#diff-f780e88b55c4f87fab261a782c1116e8c67f4bde498adae25e54fd1d375e5099L633
and 
https://github.com/xamarin/android-sdk-installer/commit/7b5c929e2895e52385035ad9bc34e7d0342b6f45
