### ISSUE TITLE
build issue typemaps.x86_64.ll: error: Could not open input file: no such file or directory

### ISSUE THREAD

**Issue by hansmbakker** [dotnet/android#8967]
### Android application type

.NET Android (net7.0-android, net8.0-android, etc.)

### Affected platform version

VS 2022 17.10 Preview 7

### Description

When trying to debug my app, I sometimes get an issue like `typemaps.x86_64.ll: error: Could not open input file: no such file or directory`.
Another error I got was `typemaps.armeabi-v7a.ll: error: Could not open input file: no such file or directory`

This happens both in Visual Studio and on the command line using MSBuild.

The build error code is `XA3006`.

### Steps to Reproduce

Not sure, but it is related to debugging on different devices having different processor architectures.

It happens e.g. when I try to deploy to my x86_64 emulator on my development machine after debugging via USB on a physical phone (which has an ARM processor).

### Did you find any workaround?

No

### Relevant log output

Please see the relevant tail of the logs below. The part before this (building the app) is common to all target devices and is working fine.

```shell
Skipping target "_LinkAssembliesNoShrink" because all output files are up-to-date with respect to the input files.
Skipping target "_GenerateJavaStubs" because all output files are up-to-date with respect to the input files.
Skipping target "_ManifestMerger" because all output files are up-to-date with respect to the input files.
Skipping target "_ConvertCustomView" because all output files are up-to-date with respect to the input files.
Skipping target "_AddStaticResources" because all output files are up-to-date with respect to the input files.
Skipping target "_GenerateEmptyAndroidRemapNativeCode" because all output files are up-to-date with respect to the input files.
Touching "obj\Debug
et8.0-android\stamp\_GeneratePackageManagerJava.stamp".
Skipping target "_GenerateAndroidAssetsDir" because all output files are up-to-date with respect to the input files.
Skipping target "_PrepareCreateBaseApk" because all output files are up-to-date with respect to the input files.
Skipping target "_CreateBaseApk" because all output files are up-to-date with respect to the input files.
Skipping target "_CompileJava" because all output files are up-to-date with respect to the input files.
[llc.EXE stderr] C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\34.0.95\tools\binutils\bin\llc.exe: error: C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\34.0.95\tools\binutils\bin\llc.exe: typemaps.x86_64.ll: error: Could not open input file: no such file or directory
XA3006: Could not compile native assembly file: typemaps.x86_64.ll

stderr | C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\34.0.95\tools\binutils\bin\llc.exe: error: C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\34.0.95\tools\binutils\bin\llc.exe: typemaps.x86_64.ll: error: Could not open input file: no such file or directory


Done building project "Anonymized.App.csproj" -- FAILED.
Build FAILED.
2>Deployment failed to Small_Phone_API_34.
2>Deploy failed
========== Build: 1 succeeded, 0 failed, 5 up-to-date, 0 skipped ==========
========== Build completed at 13:32 and took 11,768 seconds ==========
========== Deploy: 0 succeeded, 1 failed, 0 skipped ==========
========== Deploy completed at 13:32 and took 11,768 seconds ==========
```

**Comment by hansmbakker** [comment]
@grendello let's discuss the build issue here.

I recorded a binlog and can share it confidentially (it contains client information).

**Comment by hansmbakker** [comment]
The logs are shared with @grendello's Microsoft account via OneDrive

**Comment by grendello** [comment]
@hansmbakker can you modify the `C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\34.0.95\tools\Xamarin.Android.Common.targets` file and apply the following diff:

```diff
diff --git a/src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets b/src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
index 5d81e3f75..5c35118e6 100644
--- a/src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
+++ b/src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
@@ -1443,7 +1443,7 @@ because xbuild doesn't support framework reference assemblies.
 <Target Name="_GenerateJavaStubs"
     DependsOnTargets="$(_GenerateJavaStubsDependsOnTargets);$(BeforeGenerateAndroidManifest)"
     Inputs="@(_AndroidMSBuildAllProjects);@(_ResolvedUserMonoAndroidAssemblies);$(_AndroidManifestAbs);$(_AndroidBuildPropertiesCache);@(AndroidEnvironment);@(LibraryEnvironments)"
-    Outputs="$(_AndroidStampDirectory)_GenerateJavaStubs.stamp">
+    Outputs="$(_AndroidStampDirectory)_GenerateJavaStubs.stamp;@(_TypeMapAssemblySource)">
 
   <PropertyGroup>
     <_ManifestOutput Condition=" '$(AndroidManifestMerger)' == 'legacy' ">$(IntermediateOutputPath)android\AndroidManifest.xml</_ManifestOutput>
```

And see if that fixes the issue?

**Comment by hansmbakker** [comment]
I'm off until Monday and will reply when I have a chance to do it

**Comment by dezryth** [comment]
Just popping in to say I'm getting this error too, but don't think I have anything helpful to add. Let me know if there is something I could provide to assist though.

**Comment by dezryth** [comment]
@grendello I tried the change as well and it worked for me. I did not have to restart Visual Studio.

**Comment by crui3er** [comment]
Thanks @grendello. It helped to me too.

**Comment by ur3an0** [comment]
gracias @grendello, también me funciono a mi esa solución

**Comment by sabrigo** [comment]
thank you... this solved the issue

**Comment by bodeg** [comment]
@grendello 
you are a lifesaver. Thanks!

**Comment by wdcossey** [comment]
Just to confirm, it's [still] broken in Microsoft.Android.Sdk.Windows `34.0.113`

The fix by @grendello still applies

> C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\34.0.113\tools\Xamarin.Android.Common.targets

**Comment by rhires** [comment]
The fix shown in the diff worked for me.

**Comment by dellis1972** [comment]
For all of those hitting this issue (and for whom the fix worked) it would be really nice to figure out what is deleting these files in the first place. 

If you can a chance can you install the "Project System Tools" extension [1] and turn on the build logging and set it to capture All logs.  Then try to repo the issue (without the fix). We would love to figure out what is causing the problem as the code we have should be working.


[1]https://github.com/dotnet/project-system-tools

**Comment by kidmar** [comment]
This happened to me after deleting bin and obj folders.
Restarting Visual Studio without changing anything solved the problem.

**Comment by Orgbrat** [comment]
This happened to me just switching between building Windows or iOS to an Android build and deploy to emulator.
Restarting Visual Studio without changing anything solved the problem.

**Comment by dellis1972** [comment]
@Orgbrat if you can reliably reproduce it would be really handy to have all the binlog files for that process (see https://github.com/dotnet/android/issues/8967#issuecomment-2187173301). Something in that process is causing files to be deleted.

**Comment by Orgbrat** [comment]
@dellis1972  I have installed [project-system-tools](https://github.com/dotnet/project-system-tools)  as requested. I have to be away until after the holiday so I will try to reproduce and send you the logs with my details as soon as I am able.  Although it does work now, I am curious if building one of the other platforms has anything to do with this issue.

**Comment by hansmbakker** [comment]
For me it seemed to happen when switching not between platforms per se (I did not try building for windows or iOS) but switching between targets devices.

I was switching between different android phones - two physical and one emulator. There were different processor architectures.

**Comment by pjt33** [comment]
> For all of those hitting this issue (and for whom the fix worked) it would be really nice to figure out what is deleting these files in the first place.

I think it's not copying them in the first place. If I rebuild the basic template project then the only `.ll` files copied into `obj/Debug/net8.0-android/android/` are `.arm64-v8a.ll` files. When I then try to debug on an x86_x64 emulator, it copies the `.x86_x64.ll` versions of all except `typemaps`. However, the fix doesn't work for me so maybe there are multiple issues at play here.

**Comment by ziomek64** [comment]
> > For all of those hitting this issue (and for whom the fix worked) it would be really nice to figure out what is deleting these files in the first place.
> 
> I think it's not copying them in the first place. If I rebuild the basic template project then the only `.ll` files copied into `obj/Debug/net8.0-android/android/` are `.arm64-v8a.ll` files. When I then try to debug on an x86_x64 emulator, it copies the `.x86_x64.ll` versions of all except `typemaps`. However, the fix doesn't work for me so maybe there are multiple issues at play here.
> 
> Edit: a workaround for me for development is to add `<AndroidCreatePackagePerAbi>True</AndroidCreatePackagePerAbi>` to the csproj, but I suspect that I won't want that when I come to compile a bundle for release.

This workaround worked for me

**Comment by jonathanpeppers** [comment]
Does someone know the repro steps to cause this problem?

I thought that this would cause it inside Visual Studio:
* F5 to an arm64 device
* F5 to an x86_64 emulator

But that seems to work fine.

**Comment by PredatH0r** [comment]
For me it happened just now the first time after switching from the Android emulator (on x64) to a Samsung device (arm64) and then back again to the emulator.
The fix now allows me to run my app in the emulator again.

**Comment by zijianhuang** [comment]
@grendello  has given a good answer about modifying file in tools\Xamarin.Android.Common.targets

The problem has come back to me upon VS 17.11.2, now go to the targets file in 
C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\34.0.113\tools

Not sure if MS should fix this?

**Comment by grendello** [comment]
@zijianhuang it's fixed in https://github.com/dotnet/android/pull/9174
