### ISSUE TITLE
How to exclude some libraries to be trimmed in .NET 8 for Android, not MAUI?

### ISSUE THREAD

**Issue by FANMixco** [dotnet/android#8975]
### Android application type

.NET Android (net7.0-android, net8.0-android, etc.)

### Affected platform version

VS2022

### Description

I'm migrating my app from Xamarin.Android to .NET 8 and I'm getting some issues since I don't have an option to exclude some libs that existed in Xamarin:

[![Skip Libs][1]][1]

But in .NET 8 for Android in Visual Studio 2022, there is nothing like that:

[![VS 2022][2]][2]

I tried to add some code like this one in the `.csproj`:

```xml
<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
  <EnableLLVM>True</EnableLLVM>
  <JavaMaximumHeapSize>2G</JavaMaximumHeapSize>
  <AndroidKeyStore>False</AndroidKeyStore>
  <TrimMode>link</TrimMode>
  <PublishTrimmed>True</PublishTrimmed>
  <RunAOTCompilation>True</RunAOTCompilation>
  <AndroidLinkTool>r8</AndroidLinkTool>
</PropertyGroup>
<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
  <EnableLLVM>True</EnableLLVM>
  <JavaMaximumHeapSize>2G</JavaMaximumHeapSize>
  <AndroidKeyStore>False</AndroidKeyStore>
  <TrimMode>link</TrimMode>
  <RunAOTCompilation>True</RunAOTCompilation>
</PropertyGroup>
<ItemGroup>
  <TrimmerRootAssembly Include="Xamarin-MaterialSearchBar" RootMode="CopyUsed" />
</ItemGroup>
<ItemGroup>
  <TrimmerRootAssembly Include="Xamarin-MaterialSearchBar" RootMode="CopyUsed" />
</ItemGroup>
```

Or like this:

```xml
<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
  <EnableLLVM>True</EnableLLVM>
  <JavaMaximumHeapSize>2G</JavaMaximumHeapSize>
  <AndroidKeyStore>False</AndroidKeyStore>
  <TrimMode>link</TrimMode>
  <PublishTrimmed>True</PublishTrimmed>
  <RunAOTCompilation>True</RunAOTCompilation>
  <AndroidLinkTool>r8</AndroidLinkTool>
</PropertyGroup>
<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
  <EnableLLVM>True</EnableLLVM>
  <JavaMaximumHeapSize>2G</JavaMaximumHeapSize>
  <AndroidKeyStore>False</AndroidKeyStore>
  <TrimMode>link</TrimMode>
  <RunAOTCompilation>True</RunAOTCompilation>
</PropertyGroup>
<ItemGroup>
  <TrimmerRootAssembly Include="Xamarin-MaterialSearchBar" />
</ItemGroup>
```

And I got error like these ones:

> Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB4096	The item "Xamarin-MaterialSearchBar" in item list "TrimmerRootAssembly" does not define a value for metadata "RootMode"

> Severity	Code	Description	Project	File	Line	Suppression State
Error	IL1037	Invalid assembly root mode 'CopyUsed'.

> Severity	Code	Description	Project	File	Line	Suppression State
Error	NETSDK1144	Optimizing assemblies for size failed. Optimization can be disabled by setting the PublishTrimmed property to false.

Without the trimming, my app increases almost twice its size. Any idea how can I exclude this library?

  [1]: https://i.sstatic.net/WiyCZf1w.png
  [2]: https://i.sstatic.net/rUTqcKLk.png

### Steps to Reproduce

1. Try to exclude any library from being trimmed in the properties of Visual Studio:
[![VS 2022][2]][2]

### Did you find any workaround?

No, it used to work in Xamarin.Android.

### Relevant log output

```shell
N/A
```

**Comment by dellis1972** [comment]
Also based on https://learn.microsoft.com/en-gb/dotnet/core/deploying/trimming/trimming-options?pivots=dotnet-8-0#trimming-granularity you probably need to set TrimMode to partial (`<TrimMode>partial</TrimMode>`) to enable assembly level `TrimmableAssembly` items.

**Comment by FANMixco** [comment]
> TrimMode

I tried the partial one, but the error persists:

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <EnableLLVM>True</EnableLLVM>
    <JavaMaximumHeapSize>2G</JavaMaximumHeapSize>
    <AndroidKeyStore>False</AndroidKeyStore>
    <TrimMode>partial</TrimMode>
    <PublishTrimmed>True</PublishTrimmed>
    <RunAOTCompilation>True</RunAOTCompilation>
    <AndroidLinkTool>r8</AndroidLinkTool>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <EnableLLVM>True</EnableLLVM>
    <JavaMaximumHeapSize>2G</JavaMaximumHeapSize>
    <AndroidKeyStore>False</AndroidKeyStore>
    <TrimMode>link</TrimMode>
    <RunAOTCompilation>True</RunAOTCompilation>
  </PropertyGroup>
  <ItemGroup>
    <TrimmerRootAssembly Include="Xamarin-MaterialSearchBar" RootMode="CopyUsed" />
  </ItemGroup>


![image](https://github.com/xamarin/xamarin-android/assets/1666156/7afbe894-7c7b-4ac4-937c-d22918f7b511)

**Comment by FANMixco** [comment]
If I use `CopyUsed`, then I get another error:

```xml
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <EnableLLVM>True</EnableLLVM>
    <JavaMaximumHeapSize>2G</JavaMaximumHeapSize>
    <AndroidKeyStore>False</AndroidKeyStore>
    <TrimMode>CopyUsed</TrimMode>
    <PublishTrimmed>True</PublishTrimmed>
    <RunAOTCompilation>True</RunAOTCompilation>
    <AndroidLinkTool>r8</AndroidLinkTool>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <EnableLLVM>True</EnableLLVM>
    <JavaMaximumHeapSize>2G</JavaMaximumHeapSize>
    <AndroidKeyStore>False</AndroidKeyStore>
    <TrimMode>link</TrimMode>
    <RunAOTCompilation>True</RunAOTCompilation>
  </PropertyGroup>
```
![image](https://github.com/xamarin/xamarin-android/assets/1666156/9f08ac8c-bdad-4212-8746-22f22648f639)

**Comment by FANMixco** [comment]
I disabled the AOT and allowed the compilation, I kept the `CopyUsed` and even added it in the Proguard, `-keep class tk.supernovaic.MaterialSearchBar.** { *; }`:

```xml
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <EnableLLVM>True</EnableLLVM>
    <JavaMaximumHeapSize>2G</JavaMaximumHeapSize>
    <AndroidKeyStore>False</AndroidKeyStore>
    <TrimMode>CopyUsed</TrimMode>
    <PublishTrimmed>True</PublishTrimmed>
    <RunAOTCompilation>False</RunAOTCompilation>
    <AndroidLinkTool>r8</AndroidLinkTool>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <EnableLLVM>True</EnableLLVM>
    <JavaMaximumHeapSize>2G</JavaMaximumHeapSize>
    <AndroidKeyStore>False</AndroidKeyStore>
    <TrimMode>link</TrimMode>
    <RunAOTCompilation>False</RunAOTCompilation>
  </PropertyGroup>
```

But I don't think it's working at all since the library is deleted:

> Android.Views.InflateException: Binary XML file line #1 in tk.supernova.tipsal:layout/activity_main: Binary XML file line #1 in tk.supernova.tipsal:layout/app_bar_main: Error inflating class crc64f9f7571c828bfc75.MaterialSearchBar
05-22 22:53:58.370  8472  8472 I DOTNET  :  ---> Android.Views.InflateException: Binary XML file line #1 in tk.supernova.tipsal:layout/app_bar_main: Error inflating class crc64f9f7571c828bfc75.MaterialSearchBar
05-22 22:53:58.370  8472  8472 I DOTNET  :  ---> Java.Lang.Reflect.InvocationTargetException: Exception_WasThrown, Java.Lang.Reflect.InvocationTargetException
05-22 22:53:58.370  8472  8472 I DOTNET  :  ---> System.NotSupportedException: Could not activate JNI Handle 0x7ffcae9df190 (key_handle 0x93ee181) of Java type 'crc64f9f7571c828bfc75/MaterialSearchBar' as managed type 'tk.supernovaic.MaterialSearchBar.MaterialSearchBar'.

This doesn't happen if I avoid to trim it, but then the app doubles its size.

**Comment by dellis1972** [comment]
@FANMixco Looks like the valid values for `RootMode` changed in the latest versions of dotnet . See https://github.com/dotnet/runtime/blob/4c8a235abd8b510a3f8a5161bea03abd5b69896c/src/tools/illink/src/linker/Linker/AssemblyRootMode.cs#L8 for a list of valid values.

I'm not 100% what each of those do but the code for the process is at https://github.com/dotnet/runtime/blob/main/src/tools/illink/src/linker/Linker.Steps/RootAssemblyInputStep.cs#L13.

I suspect you might need a RootMode of `Library` but I could be wrong about that.

**Comment by FANMixco** [comment]
> @FANMixco Looks like the valid values for `RootMode` changed in the latest versions of dotnet . See https://github.com/dotnet/runtime/blob/4c8a235abd8b510a3f8a5161bea03abd5b69896c/src/tools/illink/src/linker/Linker/AssemblyRootMode.cs#L8 for a list of valid values.
> 
> I'm not 100% what each of those do but the code for the process is at https://github.com/dotnet/runtime/blob/main/src/tools/illink/src/linker/Linker.Steps/RootAssemblyInputStep.cs#L13.
> 
> I suspect you might need a RootMode of `Library` but I could be wrong about that.

Hi @dellis1972, but I am not sure what should I add, should I add it as one of these ones?

```xml
  <ItemGroup>
    <TrimmerRootAssembly Include="Xamarin-MaterialSearchBar" RootMode="CopyUsed" />
  </ItemGroup>
```

Or what should I do? I cannot find any documentation of the next step. At the present time, the Trimmer is not respecting what I say that it should do, and I cannot exclude the lib to be trimmed since it seems it's always trimmed.

**Comment by dellis1972** [comment]
@FANMixco so the issue is with the Visual Studio UI not providing the right options? or it breaks the settings in the csproj?

cc @tondat

**Comment by FANMixco** [comment]
> @FANMixco so the issue is with the Visual Studio UI not providing the right options? or it breaks the settings in the csproj?
> 
> cc @tondat

There are two bugs in Visual Studio:

1. You cannot exclude specific Libs. This was possible in Xamarin.Android:
[![Skip Libs][1]][1]

  [1]: https://i.sstatic.net/WiyCZf1w.png

2. You cannot revert or reach the configuration I shared if you don't modify via Code. I'm not sure if it's the default of a new project since I've been migrating everything from Xamarin.Android to .NET 8 and I was doing multiple tests in each app since I have migrated 4 apps.

**Comment by FANMixco** [comment]
> @FANMixco if its definately an issue in VS I'm sure @tondat would advise you to raise an issue using the Report an Issue menu item In visual studio, this way the issue will get routed to the correct team. The VS team use a differnt bug reporting system to this project because it is not an open source project.

Perhaps, @tondat should raise it. As a Windows Insider and someone who has reported bugs for years, I have serious doubts it would be ever considered. It would for a random pipeline waiting for votes that might never be fixed. I sound quite negative, but even recently, I reported considerable bugs in Azure and have 100% doubts, they would fix them even though the UI and links are broken, blocking any user to use them.

**Comment by jonathanpeppers** [comment]
`@(TrimmerRootAssembly)` is the replacement for the "Skip linking assemblies" project option. There is no project option page for most trimmer settings.

They have it documented here:
* https://learn.microsoft.com/dotnet/core/deploying/trimming/trimming-options#root-assemblies

And we even use it here, to preserve unit test cases:
https://github.com/xamarin/xamarin-android/blob/f5fcd4ddc5bacdb9699c50f6dad80627b80d72c8/tests/Mono.Android-Tests/Runtime-Microsoft.Android.Sdk/Mono.Android.NET-Tests.csproj#L45

Does this not work for you?

For your other comments about the IDE, can you file a `Help > Send Feedback`? We can't help much with those here.
