### ISSUE TITLE
Stop using undocumented attribute trimming

### ISSUE THREAD

**Issue by sbomer** [dotnet/android#9060]
### Android framework version

net9.0-android

### Affected platform version

.NET 9

### Description

Android should consider removing the `_AggressiveAttributeTrimming` setting, see https://github.com/dotnet/runtime/issues/88805.

Android targets are using the undocumented `_AggressiveAttributeTrimming` setting which cannot be statically validated with trim warnings. The use of this option was introduced in https://github.com/dotnet/android/pull/6563 together with NullabilityInfoContextSupport which has been removed in https://github.com/dotnet/runtime/pull/103970, so it's not clear how much size savings come from `_AggressiveAttributeTrimming` on its own.

### Steps to Reproduce

n/a

**Comment by jonathanpeppers** [comment]
I guess this was added in 60e983c6161242e0322e64c52d113e8cef2d61aa, so it's been here since .NET 6.

This means we shouldn't use any `_`-prefixed switch listed here?

* https://github.com/dotnet/runtime/blob/e5d9a3d81c830952bcf244e8e95b3afe4b8702c5/docs/workflow/trimming/feature-switches.md

**Comment by jonathanpeppers** [comment]
The only other undocumented one is `$(_SystemDiagnosticsMetricsMeterIsSupported)`. We did enable that on purpose as it contributed to a startup time regression in .NET 8.

**Comment by jonathanpeppers** [comment]
It looks like a medium-sized app is about 77kb bigger and hello world android 20kb bigger.

That seems reasonable if there is concern of something breaking from the setting.

**Comment by MichalStrehovsky** [comment]
> The only other undocumented one is `$(_SystemDiagnosticsMetricsMeterIsSupported)`. We did enable that on purpose as it contributed to a startup time regression in .NET 8.

This looks to be implemented by `Microsoft.Android.Sdk.RuntimeConfig.targets`, so it's not a "private" of the SDK, it's a private of Xamarin.

I would suggest switching to the `MetricsSupport` property and deleting all of _SystemDiagnosticsMetricsMeterIsSupported. The other one is public and documented and it looks like these two properties do the exact same thing:

https://github.com/search?q=org%3Adotnet+System.Diagnostics.Metrics.Meter.IsSupported&type=code

**Comment by jonathanpeppers** [comment]
I opened:
* https://github.com/dotnet/android/pull/9068
