### ISSUE TITLE
Crash when upgrading MAUI to 8.0.61

### ISSUE THREAD

**Issue by albilaga** [dotnet/android#9079]
### Android framework version

net8.0-android

### Affected platform version

.NET 8.0.302, MAUI 8.0.61, Rider 2024.1.4

### Description

My android app suddenly got crash after updating to 8.0.61. Not really sure what is the issue as this is suddenly just crashing. Attaching the log 
[log.txt](https://github.com/user-attachments/files/16078266/log.txt)

### Steps to Reproduce

Not really sure how to reproduce as this is on blank project 8.0.61 working fine.

### Did you find any workaround?

Use Rider EAP 2024.2 (so I am actually not sure if I should create this issue in here or in rider)

**Comment by grendello** [comment]
@albilaga can you try three things (not at the same time, one after another in the order given below) to see if any of them makes the crash disappear:

  1. Disable the interpreter by setting the `AndroidUseInterpreter` MSBuild property to `false` and then rebuild and deploy the app as usual.
  2. Close your IDE, remove the `bin` and `obj` directories throughout the source tree and then reopen the IDE and deploy as usual.
  3. Close your IDE, remove the `bin` and `obj` directories as in 1. above, then build and install the app from command prompt with:
     ```cmd
     > dotnet build -c Debug -t:Install
     ```

Also, please attach the `lib/arm64/libmonosgen-2.0.so` file from your crashing APK, thanks!

**Comment by albilaga** [comment]
@grendello now it is working again after I revert back from Rider EAP to Rider stable again. So I am not really sure. Maybe some cache on IDE. Closing it now. Thank you
