### ISSUE TITLE
Please update xamarin-android to consume zlib-ng from dotnet/runtime

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/android#9082]
### Android framework version

net9.0-android

### Affected platform version

All

### Description

The dotnet/runtime repo has migrated from consuming madler/zlib and zlib-intel to consuming zlib-ng. We merged this PR on 7/2 to achieve that: https://github.com/dotnet/runtime/issues/101465

The main issue tracking this migration effort is https://github.com/dotnet/runtime/issues/101465

In consequence, xamarin-macios and xamarin-android might need to make changes to ensure they retarget their dependencies appopriately.

Note: We ensured that mobile platforms find and consume the system-installed zlib, but are going to delete the zlib and zlib-intel references from the repo. So please help determine if you need to take actions on this repo.

This needs to be done before .NET 9 gets published.

Please let @carlossanlop or @akoeplinger know if you have any questions.

### Steps to Reproduce

-

### Did you find any workaround?

-

### Relevant log output

```shell
-
```

**Comment by dellis1972** [comment]
@grendello LibZipSharp ises zlib-ng already doesn't it?  Not sure we use it anywhere else?

**Comment by grendello** [comment]
@dellis1972 it supports it, but we use zlib for now.  There's a [draft PR](https://github.com/dotnet/android-libzipsharp/pull/145) I need to go back to.  But LibZipSharp uses its own copies of everything, due to the way it builds its support library.

I don't think we use zlib anywhere here anymore.

**Comment by jonpryor** [comment]
Should we close this issue?  I don't think it's relevant to us as-is.

**Comment by carlossanlop** [comment]
Yes, I think you can close this issue and the identical one I opened for apple mobile platforms (if you all happen to be maintainers of that repo too).

Since the zlib-ng consumption in runtime is forcing the system-installed zlib to be used in mobile platforms for now (android and apple), there's no action for you to take (assuming there's any feature here that still consumes zlib).
