### ISSUE TITLE
Cannot deploy application to Android Emulator (levels 21-23)

### ISSUE THREAD

**Issue by voroninp** [dotnet/android#9088]
### Description

I am trying to deploy application to various android versions, and I cannot do it for levels 21-23.

### Steps to Reproduce

1. Create new project with the standard MAUI template.
2. Try to run app on Android Emulator (levels 21 - 23)
3. Emulator starts, but after very long "Launching Android Emulator" VS returns an error: "There were deployment errors"
![image](https://github.com/dotnet/maui/assets/9202028/aef2989a-6922-4766-aa48-b1a18f236101)

### Version with bug

Unknown/Other

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Did you find any workaround?

No

**Comment by dellis1972** [comment]
Looks like this problem is happening because older devices are returning data from `adb shell getprop` with both `\r` and `\n`. Our parser which extracts these properties is breaking as a result.
