### ISSUE TITLE
https://aka.ms/xa5207 link is dead

### ISSUE THREAD

**Issue by matouskozak** [dotnet/android#9104]
### Android framework version

net9.0-android

### Affected platform version

NET 9.0.100-preview.5.24307.3

### Description

During build of net9.0-android MAUI app I got an error: 
`/usr/local/share/dotnet/packs/Microsoft.Android.Sdk.Darwin/34.99.0-preview.5.308/tools/Xamarin.Android.Tooling.targets(92,5): error XA5207:` and the provided link (https://aka.ms/xa5207) seems to be dead.

### Steps to Reproduce

Go to https://aka.ms/xa5207

**Comment by jpobst** [comment]
Fixed, thanks for the report!
