### ISSUE TITLE
Call site reachable warning for enums when passing it to a safe function

### ISSUE THREAD

**Issue by DavidMarquezF** [dotnet/android#9157]
### Description

There are some instances where you need to pass an enum to a function that actually handles the version correctly:

![image](https://github.com/user-attachments/assets/fa9746a9-60e3-44ff-8c7d-c4567a2cf5bb)

Internally this function will not use the flag if version is less than 24, therefore we should not get this warning. 

### Version with bug

8.0.70 SR7

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

All

### Did you find any workaround?

Ignore warning

**Comment by jpobst** [comment]
According to the documentation for [`androidx.core.app.ServiceCompat.stopForeground`](https://developer.android.com/reference/androidx/core/app/ServiceCompat?hl=en#stopForeground(android.app.Service,int)), the constant it accepts is [`androidx.core.app.ServiceCompat.STOP_FOREGROUND_REMOVE`](https://developer.android.com/reference/androidx/core/app/ServiceCompat?hl=en#STOP_FOREGROUND_REMOVE()).

You are using an enum value that is based on [`android.app.Service.STOP_FOREGROUND_REMOVE`](https://developer.android.com/reference/android/app/Service#STOP_FOREGROUND_REMOVE).

You just happened to get lucky that they have the same value, but you should be using the C# `AndroidX.Core.App.ServiceCompat.StopForegroundRemove` constant instead.

**Comment by DavidMarquezF** [comment]
Thank you so much @jpobst ! However, is it the same for the service types?
```
                    ServiceCompat.StartForeground(this, NotificationUtils.SERVICE_BIRTH_MONITOR_ALARM_NOTIFICATION_ID, GenerateNotification(), (int)ForegroundService.TypeMediaPlayback);

```

Here I get a warning on `ForegroundService.TypeMediaPlayback`
