### ISSUE TITLE
Support Fast Deployment of `@(AndroidEnvironment)`

### ISSUE THREAD

**Issue by jonpryor** [dotnet/android#9194]
### Android framework version

net9.0-android

### Affected platform version

.NET 9

### Description

Feature Request: support fast deployment of `@(AndroidEnvironment)` entries.  This is primarily to assist Aspire, which like environment variables which constantly change, so our thinking is that if we supported fast deployment of `@(AndroidEnvironment)`, then Aspire could just use an `@(AndroidEnvironment)` file(s) and the `Install` target, and we'd make things performant by *not* constantly rebuilding the `.apk`.

- [ ] Update xamarin/monodroid to fast deploy `@(AndroidEnvironment)` to e.g. `files/.__override__/env/*.txt`
- [ ] Update dotnet/android to *read* `files/.__override__/env/*.txt` during app startup.

Unspecified is *where* the `env/*.txt` files should be read.  `libmono-android*.so` is an obvious place, but increases the amount of C++ code we have hanging around.  I'm partial to `JNIEnvInit.Initialize()`: https://github.com/dotnet/android/blob/d101851ea666a0d820e3a4e4e611600f56f2a944/src/Mono.Android/Android.Runtime/JNIEnvInit.cs#L81-L118

### Steps to Reproduce

-

**Comment by dellis1972** [comment]
So the runtime already has support for reading an `environment` file from the override directly. 
https://github.com/dotnet/android/blob/main/src/native/runtime-base/android-system.cc#L642.

So we need to package up the `AndroidEnvironment` items to match the same format as the runtime is expecting and deploy it to the correct location to be picked up
