### ISSUE TITLE
Data binding options

### ISSUE THREAD

**Issue by ziomek64** [dotnet/android#9206]
### Android framework version

net8.0-android

### Description

This is not really an "issue" so to speak, but what are the current options to have UI binded to properties in code in native Android .NET then? And I don't want to explicitly set texts, images through code each time. MVVMCross seems like an overkill for me and completely overwhelming to start using. Bindings are so much easier in MAUI using XAML and INotifyPropertyChanged.

### Steps to Reproduce

.

**Comment by jpobst** [comment]
I do not believe there is any "in-box" solution.

Native Android Java Binding is not supported: https://github.com/dotnet/android/issues/7714.

That means the only available options would be a C# framework that provides that capability like MvvmCross or MAUI.

**Comment by ziomek64** [comment]
> I do not believe there is any "in-box" solution.
> 
> Native Android Java Binding is not supported: https://github.com/dotnet/android/issues/7714.
> 
> That means the only available option would be a C# framework that provides that capability like MvvmCross or MAUI.

Well, MAUI is for XAML so it's not gonna really work on native? As for mvvmcross, well..
