### ISSUE TITLE
MAUI android app build fails on a .net docker image

### ISSUE THREAD

**Issue by willbeaconAMAG** [dotnet/android#9211]
### Android framework version

net8.0-android

### Affected platform version

8.0.400

### Description

I'm attempting to build an android flavor on my .NET MAUI app on BitBucket pipelines.

The app is building in a Docker container. The image being used is the .NET 8 SDK image, mcr.microsoft.com/dotnet/sdk:8.0

I'm installing the maui-android workload onto the container. 

I'm attempting to install android dependencies as part of the dotnet build command, but and exception is being thrown by the Xamarin.Installer.Common.targets library which means the required Android SDK is not being installed, and therefore the build can't complete.

build command being used is...

dotnet build /opt/atlassian/pipelines/agent/build/App.MAUI.csproj -p:Configuration=Release -t:InstallAndroidDependencies -f net8.0-android -p:AndroidSdkDirectory="/opt/atlassian/pipelines/agent/build/android-sdk" -p:JavaSdkDirectory="/opt/atlassian/pipelines/agent/build/jdk" -p:AcceptAndroidSDKLicenses=true --runtime android-arm64 --no-restore

The error is being thrown at Xamarin.Installer.AndroidSDK.AndroidSDKContext.get_UserName()

### Steps to Reproduce

1. Start with a new, clean .NET MAUI app
2. Build the app in a Docker container (BitBucket pipelines) using the mcr.microsoft.com/dotnet/sdk:8.0 image
3. Install the maui-android workload to the container
4. Build the .NET MAUI project with the dotnet build command, and InstallAndroidDependencies parameter

### Relevant log output

```shell
10:58:30 [INF] [MAUI Build Pipeline] - DotNet Build
10:58:30 [INF] > /usr/bin/dotnet build /opt/atlassian/pipelines/agent/build/Symmetry.App.MAUI/Symmetry.App.MAUI.csproj -p:Configuration=Release -t:InstallAndroidDependencies -f net8.0-android -p:AndroidSdkDirectory="/opt/atlassian/pipelines/agent/build/android-sdk" -p:JavaSdkDirectory="/opt/atlassian/pipelines/agent/build/jdk" -p:AcceptAndroidSDKLicenses=true --runtime android-arm64 --no-restore
10:58:31 [WRN] /usr/share/dotnet/packs/Microsoft.Android.Sdk.Linux/34.0.113/tools/Xamarin.Android.Tooling.targets(70,5): warning XA5300: The Android SDK directory could not be found. Install the Android SDK by following the instructions at: https://aka.ms/dotnet-android-install-sdk [/opt/atlassian/pipelines/agent/build/Symmetry.App.MAUI/Symmetry.App.MAUI.csproj::TargetFramework=net8.0-android]
10:58:31 [WRN] /usr/share/dotnet/packs/Microsoft.Android.Sdk.Linux/34.0.113/tools/Xamarin.Android.Tooling.targets(70,5): warning XA5300: To use a custom SDK path for a command line build, set the 'AndroidSdkDirectory' MSBuild property to the custom path. [/opt/atlassian/pipelines/agent/build/Symmetry.App.MAUI/Symmetry.App.MAUI.csproj::TargetFramework=net8.0-android]
10:58:31 [WRN] /usr/share/dotnet/packs/Microsoft.Android.Sdk.Linux/34.0.113/targets/Microsoft.Android.Sdk.Tooling.targets(31,5): warning XARAT7001: System.NullReferenceException: Object reference not set to an instance of an object. [/opt/atlassian/pipelines/agent/build/Symmetry.App.MAUI/Symmetry.App.MAUI.csproj::TargetFramework=net8.0-android]
10:58:31 [WRN] /usr/share/dotnet/packs/Microsoft.Android.Sdk.Linux/34.0.113/targets/Microsoft.Android.Sdk.Tooling.targets(31,5): warning XARAT7001:    at Xamarin.Android.Tasks.ResolveAndroidTooling.RunTask() [/opt/atlassian/pipelines/agent/build/Symmetry.App.MAUI/Symmetry.App.MAUI.csproj::TargetFramework=net8.0-android]
10:58:31 [WRN] /usr/share/dotnet/packs/Microsoft.Android.Sdk.Linux/34.0.113/targets/Microsoft.Android.Sdk.Tooling.targets(31,5): warning XARAT7001:    at Microsoft.Android.Build.Tasks.AndroidTask.Execute() in /mnt/vss/_work/1/s/xamarin-android/external/xamarin-android-tools/src/Microsoft.Android.Build.BaseTasks/AndroidTask.cs:line 25 [/opt/atlassian/pipelines/agent/build/Symmetry.App.MAUI/Symmetry.App.MAUI.csproj::TargetFramework=net8.0-android]
10:58:32 [WRN] /usr/share/dotnet/packs/Microsoft.Android.Sdk.Linux/34.0.113/tools/Xamarin.Installer.Common.targets(12,3): warning : Android component "tools" is obsolete, please install "cmdline-tools" [/opt/atlassian/pipelines/agent/build/Symmetry.App.MAUI/Symmetry.App.MAUI.csproj::TargetFramework=net8.0-android]
10:58:32 [WRN] /usr/share/dotnet/packs/Microsoft.Android.Sdk.Linux/34.0.113/tools/Xamarin.Installer.Common.targets(12,3): warning : Trying to fallback to "tools"... [/opt/atlassian/pipelines/agent/build/Symmetry.App.MAUI/Symmetry.App.MAUI.csproj::TargetFramework=net8.0-android]
10:58:33 [ERR] /usr/share/dotnet/packs/Microsoft.Android.Sdk.Linux/34.0.113/tools/Xamarin.Installer.Common.targets(12,3): error : Exception caught while unzipping '/tmp/tmprjNLXJ.tmp' in '/tmp/73eb7a5d'. System.InvalidOperationException: Internal error: CommonUtilities.Helpers.UserName must have a valid value [/opt/atlassian/pipelines/agent/build/Symmetry.App.MAUI/Symmetry.App.MAUI.csproj::TargetFramework=net8.0-android]
10:58:33 [ERR] /usr/share/dotnet/packs/Microsoft.Android.Sdk.Linux/34.0.113/tools/Xamarin.Installer.Common.targets(12,3): error :    at Xamarin.Installer.AndroidSDK.AndroidSDKContext.get_UserName() in /mnt/vss/_work/1/s/xamarin-android/external/monodroid/external/android-sdk-installer/Xamarin.Installer.AndroidSDK/Xamarin.Installer.AndroidSDK/AndroidSDKContext.cs:line 26 [/opt/atlassian/pipelines/agent/build/Symmetry.App.MAUI/Symmetry.App.MAUI.csproj::TargetFramework=net8.0-android]
10:58:33 [ERR] /usr/share/dotnet/packs/Microsoft.Android.Sdk.Linux/34.0.113/tools/Xamarin.Installer.Common.targets(12,3): error :    at Xamarin.Installer.AndroidSDK.Common.BasePackage.InstallArchive(String description, String archivePath, String targetDirectory, InstallationProgressActionDelegate progressCallback) in /mnt/vss/_work/1/s/xamarin-android/external/monodroid/external/android-sdk-installer/Xamarin.Installer.AndroidSDK/Xamarin.Installer.AndroidSDK/Common/BasePackage.cs:line 601 [/opt/atlassian/pipelines/agent/build/Symmetry.App.MAUI/Symmetry.App.MAUI.csproj::TargetFramework=net8.0-android]
10:58:33 [ERR] /usr/share/dotnet/packs/Microsoft.Android.Sdk.Linux/34.0.113/tools/Xamarin.Installer.Common.targets(12,3): error : Archive '/tmp/tmprjNLXJ.tmp' installation failed with error: System.InvalidOperationException: Internal error: CommonUtilities.Helpers.UserName must have a valid value [/opt/atlassian/pipelines/agent/build/Symmetry.App.MAUI/Symmetry.App.MAUI.csproj::TargetFramework=net8.0-android]
10:58:33 [ERR] /usr/share/dotnet/packs/Microsoft.Android.Sdk.Linux/34.0.113/tools/Xamarin.Installer.Common.targets(12,3): error :    at Xamarin.Installer.AndroidSDK.AndroidSDKContext.get_UserName() in /mnt/vss/_work/1/s/xamarin-android/external/monodroid/external/android-sdk-installer/Xamarin.Installer.AndroidSDK/Xamarin.Installer.AndroidSDK/AndroidSDKContext.cs:line 26 [/opt/atlassian/pipelines/agent/build/Symmetry.App.MAUI/Symmetry.App.MAUI.csproj::TargetFramework=net8.0-android]
10:58:33 [ERR] /usr/share/dotnet/packs/Microsoft.Android.Sdk.Linux/34.0.113/tools/Xamarin.Installer.Common.targets(12,3): error :    at Xamarin.Installer.AndroidSDK.Common.BasePackage.InstallArchive(String description, String archivePath, String targetDirectory, InstallationProgressActionDelegate progressCallback) in /mnt/vss/_work/1/s/xamarin-android/external/monodroid/external/android-sdk-installer/Xamarin.Installer.AndroidSDK/Xamarin.Installer.AndroidSDK/Common/BasePackage.cs:line 601 [/opt/atlassian/pipelines/agent/build/Symmetry.App.MAUI/Symmetry.App.MAUI.csproj::TargetFramework=net8.0-android]
10:58:33 [ERR] /usr/share/dotnet/packs/Microsoft.Android.Sdk.Linux/34.0.113/tools/Xamarin.Installer.Common.targets(12,3): error :    at Xamarin.Installer.AndroidSDK.Common.BasePackage.DoInstall(String archivePath, String androidSDKRoot, InstallationProgressActionDelegate progressCallback) in /mnt/vss/_work/1/s/xamarin-android/external/monodroid/external/android-sdk-installer/Xamarin.Installer.AndroidSDK/Xamarin.Installer.AndroidSDK/Common/BasePackage.cs:line 566 [/opt/atlassian/pipelines/agent/build/Symmetry.App.MAUI/Symmetry.App.MAUI.csproj::TargetFramework=net8.0-android]
10:58:33 [ERR] /usr/share/dotnet/packs/Microsoft.Android.Sdk.Linux/34.0.113/tools/Xamarin.Installer.Common.targets(12,3): error : Installation of Android SDK component 'Android SDK Platform 34 r2 [Platform: API 34]' failed with exception. [/opt/atlassian/pipelines/agent/build/Symmetry.App.MAUI/Symmetry.App.MAUI.csproj::TargetFramework=net8.0-android]
10:58:33 [ERR] /mnt/vss/_work/1/s/xamarin-android/external/monodroid/external/android-sdk-installer/Xamarin.Installer.AndroidSDK/Xamarin.Installer.AndroidSDK/AndroidSDKContext.cs(26): error : Internal error: CommonUtilities.Helpers.UserName must have a valid value [/opt/atlassian/pipelines/agent/build/Symmetry.App.MAUI/Symmetry.App.MAUI.csproj::TargetFramework=net8.0-android]
10:58:33 [ERR] /usr/share/dotnet/packs/Microsoft.Android.Sdk.Linux/34.0.113/tools/Xamarin.Installer.Common.targets(12,3): error : Failed to install required Android SDK components. Consider setting `$(AndroidDependencyInstallationTimeout)` to a value larger than `7` minutes. [/opt/atlassian/pipelines/agent/build/Symmetry.App.MAUI/Symmetry.App.MAUI.csproj::TargetFramework=net8.0-android]
10:58:33 [ERR] /mnt/vss/_work/1/s/xamarin-android/external/monodroid/external/android-sdk-installer/Xamarin.Installer.AndroidSDK/Xamarin.Installer.AndroidSDK/AndroidSDKContext.cs(26): error : Internal error: CommonUtilities.Helpers.UserName must have a valid value [/opt/atlassian/pipelines/agent/build/Symmetry.App.MAUI/Symmetry.App.MAUI.csproj::TargetFramework=net8.0-android]
10:58:33 [DBG] 
10:58:33 [DBG] Build FAILED.
```

**Comment by jonathanpeppers** [comment]
Can you share a `.binlog`? https://aka.ms/binlog

I wonder why it shows `warning XA5300: The Android SDK directory could not be found.` so early, if it should be installing that?

**Comment by willbeaconAMAG** [comment]
> Can you share a `.binlog`? https://aka.ms/binlog
> 
> I wonder why it shows `warning XA5300: The Android SDK directory could not be found.` so early, if it should be installing that?

I don't think I will be able to generate the .binlog onto, and then extract it from the Docker container in which the BitBucket pipeline is running. The container is destroyed as soon as the build fails and finishes. I'll keep looking to see if there is a way around this.

In the meantime, I can attach the downloaded full pipeline log from Bitbucket. I'm not sure if this will give much more information, but it might highlight what I'm trying to do with loading up the container. 

What I'm trying to achieve is building the relevant projects in between SonarQube Analysis begin and end steps, so we can perform SonarQube Analysis on our BitBucket pull requests. 

[pipelineLog.txt](https://github.com/user-attachments/files/16638075/pipelineLog.txt)

**Comment by dellis1972** [comment]
Looking at the code it is using `Environment.GetEnvironmentVariable ("USER")` to get the "current user". So if the docker image does not have that info, it will fail. This is used during the extraction of the packages. 

Can you set a fake `USER` environment variable using `export USER=foo` ?

**Comment by willbeaconAMAG** [comment]
> Looking at the code it is using `Environment.GetEnvironmentVariable ("USER")` to get the "current user". So if the docker image does not have that info, it will fail. This is used during the extraction of the packages.
> 
> Can you set a fake `USER` environment variable using `export USER=foo` ?

That did the trick!

Setting a repository variable called USER was the silver bullet. Setting it with the value 'foo' allowed the build of the project to complete.

Thanks so much for the quick turnaround on this! 

Build output below...

`15:42:57 [INF] [MAUI Build Pipeline] - DotNet Build
15:42:57 [INF] > /usr/bin/dotnet build /opt/atlassian/pipelines/agent/build/Symmetry.App.MAUI/Symmetry.App.MAUI.csproj -p:Configuration=Release -t:InstallAndroidDependencies -f net8.0-android -p:AndroidSdkDirectory="/opt/atlassian/pipelines/agent/build/android-sdk" -p:JavaSdkDirectory="/opt/atlassian/pipelines/agent/build/jdk" -p:AcceptAndroidSDKLicenses=true --runtime android-arm64 --no-restore -bl
15:42:58 [WRN] /usr/share/dotnet/packs/Microsoft.Android.Sdk.Linux/34.0.113/tools/Xamarin.Android.Tooling.targets(70,5): warning XA5300: The Android SDK directory could not be found. Install the Android SDK by following the instructions at: https://aka.ms/dotnet-android-install-sdk [/opt/atlassian/pipelines/agent/build/Symmetry.App.MAUI/Symmetry.App.MAUI.csproj::TargetFramework=net8.0-android]
15:42:58 [WRN] /usr/share/dotnet/packs/Microsoft.Android.Sdk.Linux/34.0.113/tools/Xamarin.Android.Tooling.targets(70,5): warning XA5300: To use a custom SDK path for a command line build, set the 'AndroidSdkDirectory' MSBuild property to the custom path. [/opt/atlassian/pipelines/agent/build/Symmetry.App.MAUI/Symmetry.App.MAUI.csproj::TargetFramework=net8.0-android]
15:42:59 [WRN] /usr/share/dotnet/packs/Microsoft.Android.Sdk.Linux/34.0.113/targets/Microsoft.Android.Sdk.Tooling.targets(31,5): warning XARAT7001: System.NullReferenceException: Object reference not set to an instance of an object. [/opt/atlassian/pipelines/agent/build/Symmetry.App.MAUI/Symmetry.App.MAUI.csproj::TargetFramework=net8.0-android]
15:42:59 [WRN] /usr/share/dotnet/packs/Microsoft.Android.Sdk.Linux/34.0.113/targets/Microsoft.Android.Sdk.Tooling.targets(31,5): warning XARAT7001:    at Xamarin.Android.Tasks.ResolveAndroidTooling.RunTask() [/opt/atlassian/pipelines/agent/build/Symmetry.App.MAUI/Symmetry.App.MAUI.csproj::TargetFramework=net8.0-android]
15:42:59 [WRN] /usr/share/dotnet/packs/Microsoft.Android.Sdk.Linux/34.0.113/targets/Microsoft.Android.Sdk.Tooling.targets(31,5): warning XARAT7001:    at Microsoft.Android.Build.Tasks.AndroidTask.Execute() in /mnt/vss/_work/1/s/xamarin-android/external/xamarin-android-tools/src/Microsoft.Android.Build.BaseTasks/AndroidTask.cs:line 25 [/opt/atlassian/pipelines/agent/build/Symmetry.App.MAUI/Symmetry.App.MAUI.csproj::TargetFramework=net8.0-android]
15:43:00 [WRN] /usr/share/dotnet/packs/Microsoft.Android.Sdk.Linux/34.0.113/tools/Xamarin.Installer.Common.targets(12,3): warning : Android component "tools" is obsolete, please install "cmdline-tools" [/opt/atlassian/pipelines/agent/build/Symmetry.App.MAUI/Symmetry.App.MAUI.csproj::TargetFramework=net8.0-android]
15:43:00 [WRN] /usr/share/dotnet/packs/Microsoft.Android.Sdk.Linux/34.0.113/tools/Xamarin.Installer.Common.targets(12,3): warning : Trying to fallback to "tools"... [/opt/atlassian/pipelines/agent/build/Symmetry.App.MAUI/Symmetry.App.MAUI.csproj::TargetFramework=net8.0-android]
15:43:08 [DBG]   x86_64
15:43:08 [DBG]   Downloading from "https://aka.ms/download-jdk/microsoft-jdk-17.0.8-linux-x64.tar.gz" to "/opt/atlassian/pipelines/agent/build/Symmetry.App.MAUI/obj/Release/net8.0-android/android-arm64/microsoft-jdk-17.0.8-linux-x64.tar.gz" (192,261,352 bytes).
15:43:12 [DBG] 
15:43:12 [DBG] Build succeeded.
15:43:12 [DBG] 
15:43:12 [WRN] /usr/share/dotnet/packs/Microsoft.Android.Sdk.Linux/34.0.113/tools/Xamarin.Android.Tooling.targets(70,5): warning XA5300: The Android SDK directory could not be found. Install the Android SDK by following the instructions at: https://aka.ms/dotnet-android-install-sdk [/opt/atlassian/pipelines/agent/build/Symmetry.App.MAUI/Symmetry.App.MAUI.csproj::TargetFramework=net8.0-android]
15:43:12 [WRN] /usr/share/dotnet/packs/Microsoft.Android.Sdk.Linux/34.0.113/tools/Xamarin.Android.Tooling.targets(70,5): warning XA5300: To use a custom SDK path for a command line build, set the 'AndroidSdkDirectory' MSBuild property to the custom path. [/opt/atlassian/pipelines/agent/build/Symmetry.App.MAUI/Symmetry.App.MAUI.csproj::TargetFramework=net8.0-android]
15:43:12 [WRN] /usr/share/dotnet/packs/Microsoft.Android.Sdk.Linux/34.0.113/targets/Microsoft.Android.Sdk.Tooling.targets(31,5): warning XARAT7001: System.NullReferenceException: Object reference not set to an instance of an object. [/opt/atlassian/pipelines/agent/build/Symmetry.App.MAUI/Symmetry.App.MAUI.csproj::TargetFramework=net8.0-android]
15:43:12 [WRN] /usr/share/dotnet/packs/Microsoft.Android.Sdk.Linux/34.0.113/targets/Microsoft.Android.Sdk.Tooling.targets(31,5): warning XARAT7001:    at Xamarin.Android.Tasks.ResolveAndroidTooling.RunTask() [/opt/atlassian/pipelines/agent/build/Symmetry.App.MAUI/Symmetry.App.MAUI.csproj::TargetFramework=net8.0-android]
15:43:12 [WRN] /usr/share/dotnet/packs/Microsoft.Android.Sdk.Linux/34.0.113/targets/Microsoft.Android.Sdk.Tooling.targets(31,5): warning XARAT7001:    at Microsoft.Android.Build.Tasks.AndroidTask.Execute() in /mnt/vss/_work/1/s/xamarin-android/external/xamarin-android-tools/src/Microsoft.Android.Build.BaseTasks/AndroidTask.cs:line 25 [/opt/atlassian/pipelines/agent/build/Symmetry.App.MAUI/Symmetry.App.MAUI.csproj::TargetFramework=net8.0-android]
15:43:12 [WRN] /usr/share/dotnet/packs/Microsoft.Android.Sdk.Linux/34.0.113/tools/Xamarin.Installer.Common.targets(12,3): warning : Android component "tools" is obsolete, please install "cmdline-tools" [/opt/atlassian/pipelines/agent/build/Symmetry.App.MAUI/Symmetry.App.MAUI.csproj::TargetFramework=net8.0-android]
15:43:12 [WRN] /usr/share/dotnet/packs/Microsoft.Android.Sdk.Linux/34.0.113/tools/Xamarin.Installer.Common.targets(12,3): warning : Trying to fallback to "tools"... [/opt/atlassian/pipelines/agent/build/Symmetry.App.MAUI/Symmetry.App.MAUI.csproj::TargetFramework=net8.0-android]
15:43:12 [DBG]     4 Warning(s)
15:43:12 [DBG]     0 Error(s)
15:43:12 [DBG] 
15:43:12 [DBG] Time Elapsed 00:00:14.09`
