### ISSUE TITLE
`_GeneratePackageManagerJava` runs on every incremental build

### ISSUE THREAD

**Issue by jonathanpeppers** [dotnet/android#9212]
### Android framework version

net9.0-android

### Affected platform version

.NET 9

### Description

I was testing our incremental build and noticed:

1. An incremental build of a MAUI project, where I changed either C# or XAML

2. This value changes each time:

![image](https://github.com/user-attachments/assets/c5a8eeb8-dcc3-4932-82c4-245caca37e12)

![image](https://github.com/user-attachments/assets/517fff31-1b66-49aa-ba81-11d3c0992d59)

This generates a new `obj\Debug\net9.0-android\android\environment.arm64-v8a.ll` each time, causing us to run `_CompileNativeAssemblySources` each time.

Could we use the same Guid for most `Debug` builds? Would only `Release` builds need a unique Guid?

/cc @grendello 

### Steps to Reproduce

1. `dotnet new maui`
2. F5 in VS
3. Make a small code changes
4. F5 in VS

### Did you find any workaround?

No

### Relevant log output

[hellomaui_Debug_AnyCPU_Build_2024-08-16T11_28_53.1332631-05_00.binlog.zip](https://github.com/user-attachments/files/16639376/hellomaui_Debug_AnyCPU_Build_2024-08-16T11_28_53.1332631-05_00.binlog.zip)

**Comment by grendello** [comment]
I don't think even `Release` builds need a unique build id, as far as we are concerned.  The Guids we care about are the assembly MVVIDs, and that only in Release builds when marshal methods are enabled.  So we should be fine forcing the same build id in `Debug` (I wouldn't force it in `Release`, as something else somewhere may expect the id to be different).
