### ISSUE TITLE
Build task GetJavaPlatformJar occasionally fails to set JavaPlatformJarPath, causing later tasks to fail

### ISSUE THREAD

**Issue by MSLukeWest** [dotnet/android#9285]
### Android framework version

net9.0-android

### Affected platform version

9.0.100-preview.7.24407.12

### Description

Occasionally when I have my MAUI project open in Visual Studio, I see this error in the error list:

_MSB4044: The "GenerateRtxt" task was not given a value for the required parameter "JavaPlatformJarPath"_

I took a look at the .binlog file, and I see that the problem is that the GetJavaPlatformJar task that runs earlier is failing to set the JavaPlatformJarPath property.

![image](https://github.com/user-attachments/assets/6b45cdd1-cb7e-4cf3-a800-3a7070d12893)

### Steps to Reproduce

1. File -> New Project -> MAUI Application
2. Open error list
3. Build, or just wait, occasionally you'll see this error:

MSB4044: The "GenerateRtxt" task was not given a value for the required parameter "JavaPlatformJarPath"

### Did you find any workaround?

Rebuilding or reopening the project sometimes works

**Comment by dellis1972** [comment]
@MSLukeWest do you have the binlog file which contains the error?

**Comment by MSLukeWest** [comment]
[MauiApp7_Debug_AnyCPU_net9.0-android_DesignTimeBuild_2024-09-04T13_54_37.3636355-07_00.binlog.txt](https://github.com/user-attachments/files/16898241/MauiApp7_Debug_AnyCPU_net9.0-android_DesignTimeBuild_2024-09-04T13_54_37.3636355-07_00.binlog.txt)

@dellis1972 - I've attached the binlog.  I had to rename it to a .txt file because .binlog can't be attached.

**Comment by jonathanpeppers** [comment]
A guess to what's happening is:

* API 35 is not installed
* `<GetJavaPlatformJar/>` does not appear to log errors or abort the build during a `$(DesignTimeBuild)`; it can't find `android.jar` for API 35
* `<GenerateRtxt/>` has `[Required]` and so we get an error

@MSLukeWest can you confirm, you don't have this installed?

![image](https://github.com/user-attachments/assets/08e20c4b-4a99-4cc6-8fb5-2529d78810b0)

**Comment by MSLukeWest** [comment]
> A guess to what's happening is:
> 
> * API 35 is not installed
> * `<GetJavaPlatformJar/>` does not appear to log errors or abort the build during a `$(DesignTimeBuild)`; it can't find `android.jar` for API 35
> * `<GenerateRtxt/>` has `[Required] public string JavaPlatformJarPath`, and so we get an error
> 
> @MSLukeWest can you confirm, you don't have this installed?
> 
> ![image](https://private-user-images.githubusercontent.com/840039/364887290-08e20c4b-4a99-4cc6-8fb5-2529d78810b0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1NTkyMzgsIm5iZiI6MTcyNTU1ODkzOCwicGF0aCI6Ii84NDAwMzkvMzY0ODg3MjkwLTA4ZTIwYzRiLTRhOTktNGNjNi04ZmI1LTI1MjlkNzg4MTBiMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwNVQxNzU1MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNDM1YmQ0Y2ZjMTIxOGI3M2VkNjI5ZTMwNjNlN2JhMDU4NDg1MWY1MDllMDQ4NTQ3NDhlOTVhNGE3MzExYjBlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.HFidECA2keXgmVovjX7qzphJtdWHYN1gZl06hh7-Zqo)

@jonathanpeppers - I checked, and I do have this installed now.  However, I can tell by the timestamps of the folders in "Program Files (x86)\Android\android-sdk\platforms\android-35" that it wasn't installed until 1 minute after I got this error.

**Comment by jonathanpeppers** [comment]
I was able to reproduce in an integration test.

And we can fix the error message above:
* https://github.com/dotnet/android/pull/9288

But it still fails later during `<Csc/>` with:
```
UnnamedProject\MainActivity.cs(15,29): error CS0117: 'Resource' does not contain a definition for 'Layout'
UnnamedProject\MainActivity.cs(17,48): error CS0117: 'Resource' does not contain a definition for 'Id'
```
It wasn't able to generate `Resource.designer.cs` without the `android.jar` platform jar, and so the build would still fail.
