### ISSUE TITLE
Migrating AndroidX packages to `<AndroidLibrary>`

### ISSUE THREAD

**Issue by jpobst** [dotnet/android#9299]
(I made this an issue so I can provide context and we can determine the best way forward.)

Today, the AndroidX packages for an `.aar` we bind operate like this:

- `cake` unzips the `.aar` into a directory
- The project templates produces bindings using `<InputJar Include="$(extracted_dir)/classes.jar" />` (which will not ship the Java binary)
- The `.aar` is added to the NuGet package with `<None>`
- A `.targets` file is added to the NuGet package which does the following:
  - Adds the `.aar` to the application with `<AndroidAarLibrary>`

Presumably this was done to in the past to speed up user application builds instead of embedding the `.aar` as a resource in the `.dll`.

We would like to remove this "hack" and use `<AndroidLibrary>` and no `.targets` file.

However, when using `<AndroidLibrary>` and `$(AndroidGenerateResourceDesigner)`=`false`, we end up getting errors processing Android resources with `aapt`:

```
c:\code\AndroidX\generated\androidx.preference.preference\obj\Release\net8.0-android\lp\93\jl\res\color\abc_btn_colored
_text_material.xml(21): error APT2260: attribute alpha (aka Xamarin.AndroidX.Preference:alpha) not found. [c:\code\Andr
oidX\generated\androidx.preference.preference\androidx.preference.preference.csproj::TargetFramework=net8.0-android]
```

The difference is that the current `.targets`-based binding project never processes Android resources.  The consuming application would be responsible for processing them.

Should `<AndroidLibrary>` be processing the Android resources in a binding project?  Is there a way to opt out of the processing?  Or is there another way we should be going about this?

Original package example:

![image](https://github.com/xamarin/AndroidX/assets/179295/5be1ac5c-1da0-4da4-b1f4-c47c64add5ab)

**Comment by jonathanpeppers** [comment]
It seems like `AndroidGenerateResourceDesigner=false` might just have an issue where it runs targets it could skip with a `Condition`.

It is on by default, so probably not a lot of test cases turn it off:

https://github.com/dotnet/android/blob/8298b6f7698d92771c558f94d88917e2c6a96b62/src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.DefaultProperties.targets#L11

**Comment by jpobst** [comment]
`AndroidUseDesignerAssembly` = `false` seems to have fixed it, the errors have gone away.

> So in order for our build process to automatically pick up an .aar from a nuget it has to be in the same directory as the assembly.

Yes, by changing to `<AndroidLibrary>`, the `.aar` is automatically placed in the correct spot:

![image](https://github.com/xamarin/AndroidX/assets/179295/2c12ca18-4362-495e-91b3-11cae9e5f707)

Thanks for the help!
