### ISSUE TITLE
Memory leak: Android.Runtime.IdentityHashTargets and WeakReference<IJavaPeerable> when navigating between two or more activities

### ISSUE THREAD

**Issue by mattsetaro** [dotnet/android#9396]
### Android framework version

net8.0-android

### Affected platform version

.NET 8.0.402

### Description

I noticed this issue on .NET MAUI, and was able to track it down to here, .NET Android Runtime. There appears to be a memory leak when navigating between pages. I created a second activity with a button that when clicked calls Finish(), then in the MainActivity there's another button that navigates to the second activity.

App init, no navigations:
![Image](https://github.com/user-attachments/assets/96a8a347-3fb0-4fd9-bbf3-4bff811ed46e)

After about 100 navigations:
![Image](https://github.com/user-attachments/assets/a7dbad7a-fb69-4516-a39d-6eee4ddac6cc)

### Steps to Reproduce

1. Create a new .NET 8 Android application
2. In `activity_main.xml` add a button
3. In `MainActivity.cs` add the following code to the bottom of `OnCreate()`:
    1. `Button buttonToSecondActivity = FindViewById<Button>(Resource.Id.button);buttonToSecondActivity.Click += (sender, e) =>{    var intent = new Intent(this, typeof(SecondActivity));    StartActivity(intent);};`
4. Create a new XML layout called `second_activity.xml` , and add a button to the page
5. Create a new activity called `SecondActivity` and at the bottom of `OnCreate()` add the following code:
    1. `Button buttonBackToMain = FindViewById<Button>(Resource.Id.button2);buttonBackToMain.Click += (sender, e) =>{    Finish();};`
6. Run the app and click the buttons to navigate between the two pages

Here is a repo with these changes and a script to click the buttons for you: [`[m-script.sh](http://m-script.sh/)`](http://m-script.sh) — run the app in an emulator, then run that script in your terminal -- https://github.com/mattsetaro/android-memory-leaks

**Comment by mattsetaro** [comment]
I can't help but think its related to this:
```
```

**Comment by jonathanpeppers** [comment]
@mattsetaro your sample needs to call `GC.Collect()` at least once in there to be sure it's running in a determistic way:

* https://aka.ms/maui-memory-leaks

That being said, I've seen `IdentityHashTargets` in diffs of `.gcdump` files and wondered if there was an issue there. Is that the only type you see a problem with? What if you add a `GC.Collect()` call in the sample?

**Comment by jonpryor** [comment]
I believe that this is less a "bug" and more a "this is how things work (for better or worse)."

See also the [Xamarin.Android Garbage Collection](https://learn.microsoft.com/en-us/previous-versions/xamarin/android/internals/garbage-collection) documentation (which really should be migrated to .NET for Android…)

In broad strokes:

 1. Every `Java.Lang.Object` subclass holds a *JNI Global Reference* to its corresponding *Java peer*.  This JNI Global Reference *prevents* the Android VM from collecting those instances.
 2. When .NET performs a GC, any `Java.Lang.Object` subclass instances will be added to the .NET GC Finalization Queue, *but **not** finalized*.
 3. During a subsequent GC, all `Java.Lang.Object` subclasses in the finalization queue are passed to the "GC Bridge", which:

     1. "Copies over" the object graph references of (2) to their corresponding Java peers.
     2. "Toggles" the JNI Global References to JNI *Weak* Global References.
     3. Kicks off a Java-side GC
     4. "Toggles back" the JNI Weak Global References to JNI Global References
        If this "toggle back" results in the `NULL` pointer, the Java peer was collected, and we inform the .NET GC that the managed peer cal be collected.
        If this "toggle back" results in a *non*-`NULL` pointer, then the Java peer is still alive, and we inform the .NET GC that the managed peer *cannot* be collected.

Applying these broad strokes to your sample app:

  * The `AndroidApp2.MainActivity` C# instance keeps the Java peer `crc64….MainActivity` alive.
  * The `AndroidApp2.MainActivity` instance will not be collected until (1) *multiple* .NET GC's occur in which (2) the instance is added to the finalization queue, and (3) the instance is passed to the GC Bridge.
    This is likely *at least two* GCs.
  * Your app doesn't cause *any* GCs, at least until you've navigated between the pages *a lot*.

If this is a concern, there are two things you can do:

 1. Have a `GC.Collect()` invocation somewhere in your Android lifecycle code.
 2. (Optional) call `this.Dispose()` within your `MainActivity` instance when you *know* that instance will no longer be used from Java code.

**Comment by jonathanpeppers** [comment]
@mattsetaro we don't think there is an issue here, but let us know if you have other details. If you can add `GC.Collect()` calls in your app, and still see things never going away, we could investigate.
