### ISSUE TITLE
VS Terminal incorrect handling of warning messages from dotnet output

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/android#9398]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/VS-Terminal-incorrect-handling-of-warnin/10712873)._

---
Hi,

1. Open VS terminal on project
2. Run cmd file

Example cmd for publishing MAUI as apk
```
dotnet publish -c Release -r android-arm64 -p:PackageFormat=Apk -f net8.0-android
```

dotnet produces various warning messages in yellow. They seem to be missing \n terminator and overwrite line.

Output is misaligned

![Image](https://github.com/user-attachments/assets/6bb43999-5590-4f1c-ac8d-c677a7751c02)

![Image](https://github.com/user-attachments/assets/f2fe6dc1-c57d-41a3-931f-a28f8bdd9664)

---
#### evgeny.muryshkin on 7/30/2024, 03:46 PM: 

<p>Also note PS prompt and then the remainder of the output in the first screenshot. Looks like some kind of race in console.</p>

#### Feedback Bot on 7/30/2024, 06:30 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

**Comment by jpobst** [comment]
Does this only happen in the "VS Terminal" window? Or does it also happen from a normal PowerShell window outside of Visual Studio?

This should help us determine if this is an issue with the logging or specifically with the VS Terminal window.
