### ISSUE TITLE
C# type of Preference trimmed away in Release builds, causing NullReferenceException

### ISSUE THREAD

**Issue by tipa** [dotnet/android#9399]
### Android framework version

net9.0-android

### Affected platform version

.NET9 RC2

### Description

C# Type seems to be trimmed away, causing problems in Release builds.
The problem did not occur in .NET 8

### Steps to Reproduce

In my app I am using a Preference screen, with a `SwitchPreferenceCompat` specified in the XML.
```
<PreferenceScreen xmlns:app="http://schemas.android.com/apk/res-auto">
  <PreferenceCategory>
    <SwitchPreferenceCompat app:key="test" app:title="Test"/>
  </PreferenceCategory>
</PreferenceScreen>
```

In my C# code, I want to get a reference to it in order to initialize:
```
var test = FindPreference("test") as SwitchPreferenceCompat;
test.PreferenceChange += (_, _) => Toast.MakeText(Context, "toggled", ToastLength.Long).Show();
```
Example project to reproduce: [New folder.zip](https://github.com/user-attachments/files/17368684/New.folder.zip)

### Did you find any workaround?

I can use a subclass `TwoStatePreference` or just `Preference` instead the `as SwitchPreferenceCompat` case. I assume that the C# type of `SwitchPreferenceCompat` was trimmed away because no direct properties or methods of it was accessed (only of it's subclasses)

**Comment by jonathanpeppers** [comment]
The app specifies `TrimMode=full`, does the problem go away if you remove this setting? (blank would be `TrimMode=partial`)

**Comment by tipa** [comment]
No crash when I remove `TrimMode=full`. I forgot to mention that I build & deploy the app using `dotnet publish -t:Run`, it should be easy to reproduce with my example project.
I was able to resolve the problem in my project easily by casting to another (sub)class, just wanted to make sure you are aware of that edge case. I absolutely love seeing improvements to the trimmer & app size year after year. My apps were reduced by another ~20% after migrating to .NET9. Thank you!!

**Comment by jonathanpeppers** [comment]
This also fixes the sample:
```csharp
[DynamicDependency(DynamicallyAccessedMemberTypes.All, typeof(SwitchPreferenceCompat))]
public override void OnCreatePreferences(Bundle savedInstanceState, string rootKey)
```

But I'll investigate what we should do here. I suspect the "MarkJavaObjects" trimmer step could need changes here.

**Comment by jonathanpeppers** [comment]
The case is actually similar to a test we have here:

https://github.com/dotnet/android/blob/f09caedb350256df1cb8d9d6b823f28f91d0722f/tests/Mono.Android-Tests/Android.Graphics/NinePatchTests.cs#L27-L34

`NinePatchDrawable`'s constructors weren't preserved, and so we had no way to cast to it from Java via the `(IntPtr,JniHandleOwnership)` constructor.

**Comment by jonathanpeppers** [comment]
I've been debugging the trimmer to understand what is happening:

* Suppose the only usage of a type such as `NinePatchDrawable` is `d as NinePatchDrawable`, same as the issue here.

* The trimmer optimizes this completely away:

```csharp
	[Test]
	[TestCaseSource("NinePatchDrawables")]
	public void DrawableFromRes_ShouldBeTypeNinePatchDrawable(int resId, string name)
	{
		Assert.IsNotNull(Application.Context.Resources.GetDrawable(resId), "An image should have been retrieved from resource `" + name + "`.");
		Assert.IsNotNull(null, "The drawable created from resource `" + name + "` should be a NinePatchDrawable.");
	}
```
It's literally inlined to `null`!

* https://github.com/dotnet/runtime/blob/270c2b13a047d90c2050911e1232e00f0e7511a4/src/tools/illink/src/linker/Linker.Steps/MarkStep.cs#L484

This optimization pass happens during `MarkStep`, and `MarkJavaObjects` happens later. We are trying to "preserve any Java objects" that are left after `MarkStep`, but `MarkStep` is removing any usage of `NinePatchDrawable`.

Unsure what to do here yet, will discuss with our team.

**Comment by jonathanpeppers** [comment]
Another workaround is:

```xml
<PropertyGroup>
  <_ExtraTrimmerArgs>--disable-opt unusedtypechecks $(_ExtraTrimmerArgs)</_ExtraTrimmerArgs>
</PropertyGroup>
```
If a type can be created in Java, this optimization can break.

We are making this change, as it appears to affect app size only a minor amount: less than our threshold of 5% per file or 3% overall.
