### ISSUE TITLE
MAUI - Access to the path .dll is denied

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/android#9426]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/MAUI---Access-to-the-path-dll-is-denied/10760412)._

---
I created new Maui project and I cannot work due to error.
After start debugging, stop, and try to run again.

```
System.UnauthorizedAccessException: Access to the path 'C:\Users\xxx\source\repos\MauiSygic\obj\Debug\net9.0-android\android\assets\arm64-v8a\Mauixxx.dll' is denied.
1>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\35.0.0-rc.1.80\tools\Xamarin.Android.Common.targets(1415,3): error XALNS7019:    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
1>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\35.0.0-rc.1.80\tools\Xamarin.Android.Common.targets(1415,3): error XALNS7019:    at System.IO.File.InternalDelete(String path, Boolean checkHost)
1>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\35.0.0-rc.1.80\tools\Xamarin.Android.Common.targets(1415,3): error XALNS7019:    at Microsoft.Android.Build.Tasks.Files.CopyIfChanged(String source, String destination) in /Users/runner/work/1/s/xamarin-android/external/xamarin-android-tools/src/Microsoft.Android.Build.BaseTasks/Files.cs:line 125
1>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\35.0.0-rc.1.80\tools\Xamarin.Android.Common.targets(1415,3): error XALNS7019:    at Xamarin.Android.Tasks.MonoAndroidHelper.CopyAssemblyAndSymbols(String source, String destination) in /Users/runner/work/1/s/xamarin-android/src/Xamarin.Android.Build.Tasks/Utilities/MonoAndroidHelper.cs:line 344
1>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\35.0.0-rc.1.80\tools\Xamarin.Android.Common.targets(1415,3): error XALNS7019:    at Xamarin.Android.Tasks.LinkAssembliesNoShrink.CopyIfChanged(ITaskItem source, ITaskItem destination) in /Users/runner/work/1/s/xamarin-android/src/Xamarin.Android.Build.Tasks/Tasks/LinkAssembliesNoShrink.cs:line 161
1>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\35.0.0-rc.1.80\tools\Xamarin.Android.Common.targets(1415,3): error XALNS7019:    at Xamarin.Android.Tasks.LinkAssembliesNoShrink.RunTask() in /Users/runner/work/1/s/xamarin-android/src/Xamarin.Android.Build.Tasks/Tasks/LinkAssembliesNoShrink.cs:line 76
1>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\35.0.0-rc.1.80\tools\Xamarin.Android.Common.targets(1415,3): error XALNS7019:    at Microsoft.Android.Build.Tasks.AndroidTask.Execute() in /Users/runner/work/1/s/xamarin-android/external/xamarin-android-tools/src/Microsoft.Android.Build.BaseTasks/AndroidTask.cs:line 25
```

I using in project global.json:

```
{
  "sdk": {
    "version": "9.0.100-rc.1.24452.12",
    "rollForward": "latestPatch"
  }
}
```

---
#### Feedback Bot on 10/4/2024, 01:14 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Samantha Houts [MSFT] on 10/14/2024, 00:46 PM: 

<p>Sometimes we see this when the path is too long. If you move your project to a shorter path, does it build? Does this happen with every project or just this one? Does it happen every build? Thanks!</p>
<p><strong>Why do we ask for more info?</strong><br>
We try to reproduce all issues reported with the information provided in the description and comments. When we can’t reproduce the issue, we ask you for more information so we can resolve the issue as quickly and efficiently as possible.<br>
In our <a target='_blank' href="https://aka.ms/vsfeedbackguidelines/#writing-a-good-bug-report-or-feature-suggestion">guidelines</a>, you can get tips on how to provide clear and simple reproducible steps.</p>

#### Kopernik Mikolaj on 10/18/2024, 00:44 AM: 

(private comment, text removed)

**Comment by samhouts** [comment]
@dellis1972 maybe another thing to be resolved by https://github.com/dotnet/android/pull/9423?

**Comment by dellis1972** [comment]
Possibly yes :D

**Comment by dellis1972** [comment]
More likely resolved by https://github.com/dotnet/android-tools/pull/245 and https://github.com/dotnet/android/pull/9423

**Comment by jonpryor** [comment]
Please try again with .NET 9 GA.  The various fixes to try to improve this scenario (be53aed593ffc3863d3df1114d97d2b5e1d6239f, others) are only in .NET 9 GA.

**Comment by autoprog** [comment]
hi,

Delete folders Obj and Bin, open solution ok.
my case solved.
thanks.

**Comment by eerojaaskelainen** [comment]
Issue seems to exist in latest .NET 9 version also. If it matters, mine is a multi-project app (migrated from Xamarin.Forms).

Versions:
- Visual Studio: 17.12.3
- .NET: 9.0.101
- MAUI: 9.0.10

Initial builds work OK, but rebuild fails. 

Build output:
```
2>Done building project "MyApp.Droid.csproj".
2>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\35.0.7\tools\Xamarin.Android.Common.targets(1420,3): error XALNS7019: System.UnauthorizedAccessException: Access to the path 'C:\Temp\MyApp\obj\Debug\net9.0-android\android\assets\x86_64\MyApp.Droid.dll' is denied.
2>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\35.0.7\tools\Xamarin.Android.Common.targets(1420,3): error XALNS7019:    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
2>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\35.0.7\tools\Xamarin.Android.Common.targets(1420,3): error XALNS7019:    at System.IO.File.InternalDelete(String path, Boolean checkHost)
2>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\35.0.7\tools\Xamarin.Android.Common.targets(1420,3): error XALNS7019:    at Microsoft.Android.Build.Tasks.Files.CopyIfChangedOnce(String source, String destination) in /Users/runner/work/1/s/xamarin-android/external/xamarin-android-tools/src/Microsoft.Android.Build.BaseTasks/Files.cs:line 197
2>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\35.0.7\tools\Xamarin.Android.Common.targets(1420,3): error XALNS7019:    at Microsoft.Android.Build.Tasks.Files.CopyIfChanged(String source, String destination) in /Users/runner/work/1/s/xamarin-android/external/xamarin-android-tools/src/Microsoft.Android.Build.BaseTasks/Files.cs:line 176
2>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\35.0.7\tools\Xamarin.Android.Common.targets(1420,3): error XALNS7019:    at Xamarin.Android.Tasks.MonoAndroidHelper.CopyAssemblyAndSymbols(String source, String destination) in /Users/runner/work/1/s/xamarin-android/src/Xamarin.Android.Build.Tasks/Utilities/MonoAndroidHelper.cs:line 394
2>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\35.0.7\tools\Xamarin.Android.Common.targets(1420,3): error XALNS7019:    at Xamarin.Android.Tasks.LinkAssembliesNoShrink.CopyIfChanged(ITaskItem source, ITaskItem destination) in /Users/runner/work/1/s/xamarin-android/src/Xamarin.Android.Build.Tasks/Tasks/LinkAssembliesNoShrink.cs:line 161
2>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\35.0.7\tools\Xamarin.Android.Common.targets(1420,3): error XALNS7019:    at Xamarin.Android.Tasks.LinkAssembliesNoShrink.RunTask() in /Users/runner/work/1/s/xamarin-android/src/Xamarin.Android.Build.Tasks/Tasks/LinkAssembliesNoShrink.cs:line 76
2>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\35.0.7\tools\Xamarin.Android.Common.targets(1420,3): error XALNS7019:    at Microsoft.Android.Build.Tasks.AndroidTask.Execute() in /Users/runner/work/1/s/xamarin-android/external/xamarin-android-tools/src/Microsoft.Android.Build.BaseTasks/AndroidTask.cs:line 25
```

**Comment by FM1973** [comment]
I got the same problem and it is really annoying.
I currently use "taskkill /IM "msbuild.exe" /F" but this is just a workaround...

**Comment by rogue-pogue** [comment]
Same problem

**Comment by tranb3r** [comment]
Same problem.
@jonpryor Why is this issue closed? Has it been fixed? In which release?

**Comment by uholeschak** [comment]
At least I have this issue also in 17.12.3. This is absolutely nerving. You always have to delete the obj dir before the every build.

**Comment by dberroa** [comment]
I started a brand new MAUI .net 9 project yesterday and am also experiencing this after building and running the Android version the second time. First time works in the emulator and second time says the file access is denied. Running the cmd "taskkill /IM "msbuild.exe" /F" like mentioned above does fix it for me. Restarting visual studio also fixes it but it's very annoying and slow to run the app, make a change, close VS studio, reopen and load, run again.

**Comment by erosxdev** [comment]
after experiencing this on a fresh win 11 + latest VS, I have only 2 questions:
J F C! Are you trying to kill maui all by yourselves no competition needed?  
Do you even know the concept of release vs dev build and that dev build are not for general public?

**Comment by uholeschak** [comment]
This is fixed after updating with: `dotnet workload update`

**Comment by carljohansen** [comment]
`dotnet workload update` fixed it for me.  BTW - it took several attempts to get the command to work.  It kept failing part way through (and then crashed while trying to roll back).  It worked when I ran it from an admin PowerShell.
