### ISSUE TITLE
Profiling .NET MAUI Android Apps

### ISSUE THREAD

**Issue by ShubhamSh04** [dotnet/android#9439]
### Android framework version

net8.0-android

### Affected platform version

Android 11

### Description

![Image](https://github.com/user-attachments/assets/2decdb57-b415-47a6-9675-fbd3d21d91f5)

### Steps to Reproduce

Created the Sample Maui App.
Trying to implement the profiling in android app.
Following this article "https://github.com/dotnet/android/blob/main/Documentation/guides/tracing.md?plain=1"
After executing the "dotnet-trace collect -p 38604 --format speedscope" command facing the below issue I had also attached the screenshot of the same![Image](https://github.com/user-attachments/assets/be525069-4b09-407a-b4c0-a26cf274ed1c)
.
System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
   at System.IO.BinaryReader.InternalRead(Int32 numBytes)

Thanks for the help !!

**Comment by jonathanpeppers** [comment]
I have a YouTube video on `dotnet-trace`, etc. I would guess there is probably a step you've missed:
* https://youtu.be/hIYwz5dsZ6M

**Comment by jonpryor** [comment]
Did the YouTube video help?
