### ISSUE TITLE
Documentation Layout Binding

### ISSUE THREAD

**Issue by christophechateau** [dotnet/android#9440]
### Android framework version

net8.0-android

### Affected platform version

NET 8.0

### Description

Hi,

First thanks for the work around the android dotnet runtime !

Until the end of Xamarin support (may 2024), there is some confusion in naming and technology choice with : 

- Xamarin was retired but finally rebranded as dotnet android.
- Microsoft pushing so hard to NET MUI so every google results or documention looking for "dotnet android" are redirected to NET MAUI.
- the new "dotnet android" stuff is great but lack of many examples or snippets even if 80% of time mix java && xamarin doc does the job.

Now, i'm looking for a documentation, snippet or any example on how to do layout binding with dotnet android.

Thanks for you light

### Steps to Reproduce

-

**Comment by jpobst** [comment]
If you are referring to Layout Binding, here is the documentation for that:
https://learn.microsoft.com/en-us/dotnet/android/features/layout-code-behind/

If you are referring to DataBinding, there is no built-in solution: 
https://github.com/dotnet/android/issues/7714.

The Java DataBinding libraries will not work, so you'll need a framework that runs on top of .NET for Android that provides that capability like MAUI or MvvmCross.

Additionally, here's the documentation for Xamarin.Android. Unfortunately it was delisted from search engines, but 99% of it is still applicable to .NET for Android:
https://learn.microsoft.com/en-us/previous-versions/xamarin/android

**Comment by christophechateau** [comment]
thanks for your help.

I already saw the [layout-code-behind](https://learn.microsoft.com/en-us/dotnet/android/features/layout-code-behind/). 
It's more a microsoft designation for object mapping : the mapping between XML components and C# object.

I get a pointer to the [AndroidX.DataBinding](https://www.nuget.org/packages?q=AndroidX.DataBinding) from the discord channel. It seems closest to what i need, i will look into it.
