### ISSUE TITLE
Android: Error in migrating Android specific Resources (AndroidResource) from Xamarin Forms to MAUI Android (R.java error)

### ISSUE THREAD

**Issue by muffadal53** [dotnet/android#9461]
### Description

We are migrating Resources of Android specific Resources (controls, colors)  like .xml, .axml and .png files from Xamarin Forms to "MAUI->Platforms->Android->Resources" folder and getting error "**APT2258	invalid symbol name 'com.companyname.mauiapp1:drawable/import'.
	C:\Users\*User*\AppData\Local\Temp\2kevcthb.kih\com\companyname\mauiapp1\R.java**"

I thought a per the thing mentioned in Blog "https://devblogs.microsoft.com/dotnet/android-resource-designer-dotnet-8/" this will automatically work but this is not the case with .Net 8.

### Steps to Reproduce

1. Copy the Resources file from Xamarin Forms Android specific resources.
2. Move the resources (controls, colors)  like .xml, .axml and .png etc. under "MAUI/Platforms/Android/Resources" folder structure as follows:
 
 a. Android\Resources\color\
 b. Android\Resources\drawable\
 c. Android\Resources\drawable-hdpi\
 d. Android\Resources\drawable-ldpi\
 e. Android\Resources\drawable-mdpi\
 f. Android\Resources\drawable-xhdpi\
 g. Android\Resources\drawable-xxhdpi\
 h. Android\Resources\drawable-xxxhdpi\
 i. Android\Resources\layout\
 j. Android\Resources\values\

3. And when we compile the solution we get following error which is as follows:

"**APT2258	invalid symbol name 'com.companyname.mauiapp1:drawable/import'.
	C:\Users\*User*\AppData\Local\Temp\2kevcthb.kih\com\companyname\mauiapp1\R.java**"

Please let me know how can we solve this issue for MAUI migration.

### Link to public reproduction project repository

https://github.com/muffadal53/MAUIAndroid_Resource

### Version with bug

8.0.80 SR8

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android

### Did you find any workaround?

N/A

### Relevant log output

```shell
N/A
```

**Comment by dellis1972** [comment]
PR is up https://github.com/dotnet/android/pull/9537
