### ISSUE TITLE
NullReferenceException in FastDeploy

### ISSUE THREAD

**Issue by dotMorten** [dotnet/android#9514]
### Android framework version

net9.0-android

### Affected platform version

VS2022 17.12

### Description

Something was going wrong with ADB, but it resulted in a nullref exception in FastDeploy.
I can't see the source, but the error should be clear enough to where the null-check should be added and provide a better error about what went wrong:
![Image](https://github.com/user-attachments/assets/f351c4c0-6bc4-41c2-a2b3-708c177ddcbb)

### Steps to Reproduce

I'm honestly not sure. Emulators were in a bad state in general, and required a system restart to start connecting again.

### Did you find any workaround?

Restart Windows.

### Relevant log output

```shell

```

**Comment by dellis1972** [comment]
Fix via https://github.com/xamarin/monodroid/pull/1557

**Comment by jonathanpeppers** [comment]
Private sources for `<FastDeploy/>` are updated in:
* https://github.com/dotnet/android/pull/9541 (main)
* https://github.com/dotnet/android/pull/9539 (.NET 9 servicing)

These both contain the NRE fix. Thanks!
