### ISSUE TITLE
Fail to compile MAUI Blazor Android only in Release build when there is a file starting with dot (.) in wwwroot folder

### ISSUE THREAD

**Issue by datvm** [dotnet/android#9542]
### Description

When compile a MAUI Blazor project for Android in Release build, if there is a file like `.init` in `wwwroot` file, it fails with the following message:

```
PS C:\Users\lukev\source\repos\ConsoleApp1\MauiApp1> dotnet build -f:net8.0-android -c:Release
  Determining projects to restore...
  Restored C:\Users\lukev\source\repos\ConsoleApp1\MauiApp1\MauiApp1.csproj (in 1.28 sec).
  MauiApp1 -> C:\Users\lukev\source\repos\ConsoleApp1\MauiApp1\bin\Release\net8.0-android\MauiApp1.dll
C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\34.0.95\targets\Microsoft.Android.Sdk.ILLink.targets(34,11): error MSB4186: Invalid stat
ic method invocation syntax: "[System.String]::Copy().StartsWith ('Xamarin.AndroidX.')". Method 'System.String.Copy' not found. Static method invoca
tion should be of the form: $([FullTypeName]::Method()), e.g. $([System.IO.Path]::Combine(`a`, `b`)). Check that all parameters are defined, are of
the correct type, and are specified in the right order. [C:\Users\lukev\source\repos\ConsoleApp1\MauiApp1\MauiApp1.csproj::TargetFramework=net8.0-an
droid]
    0 Warning(s)
    4 Error(s)
```

Renaming/removing the file would make the error go away but sometimes it's not an option.

This is my workload because I am not sure which to pick from the list:

```
Installed Workload Id      Manifest Version       Installation Source
---------------------------------------------------------------------------------
android                    34.0.95/8.0.100        SDK 8.0.300, VS 17.10.34928.147
aspire                     8.0.1/8.0.100          SDK 8.0.300, VS 17.10.34928.147
ios                        17.2.8053/8.0.100      SDK 8.0.300, VS 17.10.34928.147
maccatalyst                17.2.8053/8.0.100      SDK 8.0.300, VS 17.10.34928.147
maui-windows               8.0.21/8.0.100         SDK 8.0.300, VS 17.10.34928.147
wasi-experimental          8.0.6/8.0.100          SDK 8.0.300
```

### Steps to Reproduce

1. Create a new project using .NET 8 MAUI Blazor Hybrid template.
2. Create a new file (Ctrl Shift A in Visual Studio) in `wwwroot` folder and name it something like `.init`.
3. Build the project in Release mode: `dotnet build -f:net8.0-android -c:Release`

### Version with bug

Unknown/Other

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

**Comment by jonathanpeppers** [comment]
@datvm we removed the code mentioned above (`Microsoft.Android.Sdk.ILLink.targets(34,11)`) in https://github.com/dotnet/android/commit/a34988cf5623ec25e13dca39d1337e8e606f6fc0, which is in .NET 9.

Is this problem gone in .NET 9?

**Comment by datvm** [comment]
@jonathanpeppers yes I can confirm the issue does not happen in .NET 9 anymore. I assume it won't be backported to .NET 8?

**Comment by jonathanpeppers** [comment]
@datvm .NET 8 is "done" in that is will probably only get security fixes from now on. .NET 8 Android may/may not have another release.

If we end up spinning another build, I'll put this on our list to backport. Thanks!
