### ISSUE TITLE
Failure [INSTALL_FAILED_NO_MATCHING_ABIS: Failed to extract native libraries, res=-113]

### ISSUE THREAD

**Issue by JaneySprings** [dotnet/android#9567]
### Android framework version

net9.0-android

### Affected platform version

.NET 9

### Description

I'm trying to build MAUI app with net9.0, but sometimes it builds only `arm64` version (I have x86_64 AVD running):
![Image](https://github.com/user-attachments/assets/27f6f324-fc5d-4ad4-a173-d897abee6cb3)

I have tried to pass the `-p:AndroidSupportedAbis=x86_64` property, but it doesn't  work.

[msbuild.binlog.zip](https://github.com/user-attachments/files/17977492/msbuild.zip)

### Steps to Reproduce

Random (I can't understand what was a reason of it)

### Did you find any workaround?

Pass `-p:RuntimeIdentifier=android-x64`

### Relevant log output

```shell
adb: failed to install C:\...\maui-Signed.apk: Failure [INSTALL_FAILED_NO_MATCHING_ABIS: Failed to extract native libraries, res=-113]
```

**Comment by dellis1972** [comment]
Ah its a maui app. 

try
```
dotnet build <yourapp.csproj> -f net9.0-android -t:Install -bl 
```

**Comment by dellis1972** [comment]
According to that build log you have a global `RuntimeIdentifier` set 

```
RuntimeIdentifier = android-arm64
```

Do you have `RuntimeIdentifier` or `RuntimeIdentifiers` set anywhere in your project or in a Directory.Build.props anywhere?

**Comment by JaneySprings** [comment]
No, I just created a new .NET MAUI app in the `C:\`. Same issue:
![Image](https://github.com/user-attachments/assets/b3b34210-99de-40cf-8e0f-4d3ab35db7fd)

### Binlog
[msbuild.binlog.zip](https://github.com/user-attachments/files/17978622/msbuild.binlog.zip)

**Comment by jonathanpeppers** [comment]
The default is:

https://github.com/dotnet/android/blob/b870836db01089e3e57bd68064ab3cc4e7494899/src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.DefaultProperties.targets#L89

@dellis1972 is maybe some newer Android emulator reporting arm64 when it shouldn't?

![Image](https://github.com/user-attachments/assets/715ef09d-130b-475d-ad30-05da8ca395b1)

@JaneySprings do you by chance have a device plugged in, the same time as running an emulator?

**Comment by jonathanpeppers** [comment]
Does everything work as expected if you unplug the phone and only use the emulator?

I'm wondering if the build step finds the phone, and then deploy somehow runs against the emulator.

**Comment by JaneySprings** [comment]
Yes, it works without my phone. 
It means that I can’t build an application if I have running AVD and connected phone?

**Comment by jonathanpeppers** [comment]
> It means that I can’t build an application if I have running AVD and connected phone?

I do this frequently, but I'm using an IDE like Visual Studio or VS Code + MAUI extension. They have a dropdown that passes `-p:AdbTarget` to select a device, and things seem to work that way.

Is this problem happening at the command-line?

**Comment by JaneySprings** [comment]
> Is this problem happening at the command-line?

Yes (check the last screenshots)

We have PC with Azure Pipelines Agent and connected Android device for the Gradle device tests (Native code). We have incorrect `.apk` file if we build our application in this runner.

Also we have Android Tablet with `Intel Atom` CPU. How will it choose the `abi` for application if I connect it with regular phone? Both `x64 and arm` or `FirstOrDefault`?

**Comment by JaneySprings** [comment]
@jonathanpeppers Is there a property that allows you to disable `_GetPrimaryCpuAbi` task and return `net8.0` behavior?

**Comment by jonathanpeppers** [comment]
> [@jonathanpeppers](https://github.com/jonathanpeppers) Is there a property that allows you to disable `_GetPrimaryCpuAbi` task and return `net8.0` behavior?

To my knowledge, the behavior in .NET 9 is the same here.

> We have PC with Azure Pipelines Agent and connected Android device for the Gradle device tests (Native code). We have incorrect .apk file if we build our application in this runner.

If you are testing on CI, can you use a Release build instead? This will skip all "fast deployment" logic for Debug scenarios. That seems more appropriate anyway. Alternatively, you could set `-p:EmbedAssembliesIntoApk=true` for CI only.

**Comment by dellis1972** [comment]
as @jonathanpeppers said `EmbedAssembliesIntoApk` is the property which will disable fast deployment completely.

If you want to force an ABI, you might want to try setting `AdbTargetArchitecture` to your target. it will override the values which `_GetPrimaryCpuAbi` calculate. This is the property which the IDE's use to skip the device abi detection, since that already have that info.

**Comment by JaneySprings** [comment]
Yes, `<AdbTargetArchitecture>arm64-v8a;x86_64</AdbTargetArchitecture>` or `-p:AdbTarget=-s%20emulator-5554` work. OK, That's enough. Thank you @dellis1972 and @jonathanpeppers

**Comment by dellis1972** [comment]
If you are building a Release build , fast deployment is turned off so this will not happen.
