### ISSUE TITLE
AndroidMessageHandler seems to be ignoring ClientCertificates

### ISSUE THREAD

**Issue by nk-alex** [dotnet/android#9576]
### Description

I have an old .net framework 4.5 project using **HttpClient** with **HttpClientHandler** in order to load client certificate for query. This is the code I'm using. Works as expected:

```
var handler = new HttpClientHandler();
handler.ClientCertificateOptions = ClientCertificateOption.Manual;
handler.SslProtocols = SslProtocols.Tls12;
handler.ClientCertificates.Add(new X509Certificate2(certificate, password));

using (var httpClient = new HttpClient(handler))
{
    var httpRequest = new HttpRequestMessage(HttpMethod.Post, uri)
    {
        Content = new StringContent(body, Encoding.UTF8, "text/xml")
    };
    httpRequest.Headers.Add("SOAPAction", action);
    var httpResponse = await httpClient.SendAsync(httpRequest);
}
```

Now I'm trying to recreate that code on my .net 8 MAUI project. I started with the Android specific code:

```
#if ANDROID
                var handler = new AndroidMessageHandler();
                handler.ClientCertificateOptions = ClientCertificateOption.Manual;
                handler.SslProtocols = SslProtocols.Tls12;
                handler.ClientCertificates = new X509CertificateCollection { new X509Certificate2(certificate,  password) };
#else

#endif

                using (var httpClient = new HttpClient(handler))
                {
                    var httpRequest = new HttpRequestMessage(HttpMethod.Post, uri)
                    {
                        Content = new StringContent(body, Encoding.UTF8, "text/xml")
                    };
                    httpRequest.Headers.Add("SOAPAction", action);
                    var httpResponse = await httpClient.SendAsync(httpRequest);
                }
```

But the web service I'm sending my request keeps on returning me **403 - No certificate detected**.

- The web service mentioned above is from a third-party. I don't have control over it.
- I'm using the same message and certificate on both my .net framework application and MAUI application. Since in .net framework this is working, my best guess is I'm either not using **AndroidMessageHandler** as intended, or [this issue](https://github.com/dotnet/android/issues/7274) is still around.

### Steps to Reproduce

-

### Version with bug

8.0.100 SR10

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 14

### Did you find any workaround?

-

### Relevant log output

```shell

```

**Comment by jpobst** [comment]
It looks like the fixed issue you reference was fixed in July 2024, so it would likely only be in .NET 9 and not .NET 8.

https://github.com/dotnet/android/pull/8961

Can you try on .NET 9 and see if it works there?

**Comment by jpobst** [comment]
> Just to know, are there any plans on implementing this solution also for .NET8?

I will defer to @simonrozsival and @jonpryor about the risk involved with backporting this to .NET 8.

**Comment by filipnavara** [comment]
The implementation on .the .NET runtime side needed to add a Java library to handle the callbacks. This was rather big change that would be non-trivial to backport (especially due to the fact that it required changes across more repositories to account for the extra library).

**Comment by jpobst** [comment]
I think this is our official-ish policy on .NET 8 now, so a backport isn't likely:

> .NET 8 is "done" in that is will probably only get security fixes from now on. .NET 8 Android may/may not have another release.
