### ISSUE TITLE
Incremental build issue when adding Android resource

### ISSUE THREAD

**Issue by jpobst** [dotnet/android#9588]
### Android framework version

net9.0-android

### Affected platform version

.NET 9.0.101

### Description

Adding a new Android resource to a project causes the incremental build to error with:

```
Resources\layout\activity_two.xml error APT2126: file not found.
```

This error comes from the `Aapt2Compile` task.  It is looking for `\obj\Debug\net9.0-android\res\layout\activity_two.xml` but that file doesn't exist.  Presumably some previous incremental step is not running and copying it there?

[binlog.zip](https://github.com/user-attachments/files/18012999/binlog.zip)

### Steps to Reproduce

```console 
dotnet new android
dotnet build -bl
copy Resources\layout\activity_main.xml Resources\layout\activity_two.xml
dotnet build -bl
```

**Comment by dellis1972** [comment]
Yes, this is a modified date issue. the new file has a modified date time earlier than the `obj\Debug\net9.0-android\res.flag`. 
So `_GenerateAndroidResourceDir` is skipped. 
I'll add a check for file hashes.
