### ISSUE TITLE
Unable to use RequestCallEndpointChange method

### ISSUE THREAD

**Issue by yeahg-dev** [dotnet/android#9602]
### Android framework version

net9.0-android

### Affected platform version

.NET9.0, VisualStudioCode 1.95.3

### Description

Unable to call RequestCallEndpointChange method 

### as-is

I tried to call `RequestCallEndpointChange` with argument which type is`CallEndPointType`, but failed with errors.

- 'CallEndpoint.TypeSpeaker' is obsolete: 'This constant will be removed in the future version. Use Android.Telecom.CallEndpointType enum directly instead of this field.'[CS0619](https://msdn.microsoft.com/query/roslyn.query?appId=roslyn&k=k(CS0619))
- Argument 1: cannot convert from 'Android.Telecom.CallEndpointType' to 'Android.Telecom.CallEndpoint'[CS1503](https://msdn.microsoft.com/query/roslyn.query?appId=roslyn&k=k(CS1503))

![Image](https://github.com/user-attachments/assets/a490a263-dba7-4c3d-b763-5f340196f4cc)

```C#
        //     Portions of this page are modifications based on work created and shared by the
        //     Android Open Source Project and used according to terms described in the Creative
        //     Commons 2.5 Attribution License.
        [Register("requestCallEndpointChange", "(Landroid/telecom/CallEndpoint;Ljava/util/concurrent/Executor;Landroid/os/OutcomeReceiver;)V", "", ApiSince = 34)]
        [SupportedOSPlatform("android34.0")]
        public void RequestCallEndpointChange(CallEndpoint endpoint, IExecutor executor, IOutcomeReceiver callback);
```

### should-be
`RequestCallEndpointChange` should support `CallEndPointType` argument.

### Steps to Reproduce

1. make mobile project with Uno platform, .net 9
2. call `Connction.RequestCallEndpointChange`

### Did you find any workaround?

no

### Relevant log output

```shell

```

**Comment by jpobst** [comment]
It looks like you are trying to use `Android.Telecom.CallEndpoint` as an enum (with the `TypeSpeaker` value) rather than using it as a class.

I think you need to create an instance of `CallEndpoint` and pass that to `RequestCallEndpointChange`:

```csharp
var endpoint = new CallEndpoint ("name", CallEndpointType.TypeSpeaker, uuid);
```

[Documentation](https://learn.microsoft.com/en-us/dotnet/api/android.telecom.callendpoint?view=net-android-34.0)

**Comment by yeahg-dev** [comment]
Thanks It works!
