### ISSUE TITLE
I need help to this: CODE ERRO; XALNS7028

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/android#9616]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/I-need-help-to-this:-CODE-ERRO;-XALNS702/10799206)._

---
[severity:It's more difficult to complete my work]
System.IO.FileNotFoundException: Could not load assembly 'System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. Perhaps it doesn't exist in the Mono for Android profile?
Nombre de archivo: 'System.Windows.Forms.dll'
   en Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.Resolve(AssemblyNameReference reference, ReaderParameters parameters) en /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop.Tools.Cecil/Java.Interop.Tools.Cecil/DirectoryAssemblyResolver.cs:línea 278
   en Mono.Cecil.MetadataResolver.Resolve(TypeReference type) en /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/external/cecil/Mono.Cecil/MetadataResolver.cs:línea 111
   en Mono.Cecil.TypeReference.Resolve() en /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/external/cecil/Mono.Cecil/TypeReference.cs:línea 278
   en Java.Interop.Tools.Cecil.TypeDefinitionCache.Resolve(TypeReference typeReference) en /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop.Tools.Cecil/Java.Interop.Tools.Cecil/TypeDefinitionCache.cs:línea 20
   en Java.Interop.Tools.Cecil.TypeDefinitionRocks.&lt;GetTypeAndBaseTypes&gt;d__5.MoveNext() en /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop.Tools.Cecil/Java.Interop.Tools.Cecil/TypeDefinitionRocks.cs:línea 36
   en Java.Interop.Tools.Cecil.TypeDefinitionRocks.IsSubclassOf(TypeDefinition type, String typeName, IMetadataResolver resolver) en /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop.Tools.Cecil/Java.Interop.Tools.Cecil/TypeDefinitionRocks.cs:línea 87
   en MonoDroid.Tuner.FixAbstractMethodsStep.FixAbstractMethods(AssemblyDefinition assembly)
   en Xamarin.Android.Tasks.LinkAssembliesNoShrink.RunTask()
   en Microsoft.Android.Build.Tasks.AndroidTask.Execute() en /Users/runner/work/1/s/xamarin-android/external/xamarin-android-tools/src/Microsoft.Android.Build.BaseTasks/AndroidTask.cs:línea 25

---
#### Feedback Bot on 11/25/2024, 06:13 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Dean Ellis [MSFT] on 11/26/2024, 07:00 AM: 

<p>Looks like you have a reference or package reference that is using System.Windows.Forms.<br>
System.Windows.Forms does not work on android.You will need to look at the references you have and remove the one which is using System.Windows.Forms.</p>

**Comment by jpobst** [comment]
It doesn't look like there has been any customer response since our solution, gonna assume this one is solved.
